-- main.lua -- TI-Nspire presentation layer: drawing, input, timing.
--
-- Rules live in src/klondike/game.lua. `platform.apilevel` is emitted as the
-- first line of the bundle by tools/bundle.py, so it is intentionally absent
-- here.
--
-- When bundled, `Klondike` is already a local from the inlined module; the
-- `Klondike or require` form below also lets this file load under a desktop
-- Lua.
local Klondike = Klondike or require("game")

-- ------------------------------------------------------------------ tuning --
-- Klondike is strictly turn-based, so there is no game loop and no animation:
-- every repaint is caused by a key. The timer runs only so that idle time on
-- the title screen can be counted into the seed -- see newSeed.
local BASE_TICK = 0.05

-- The fan. A column can hold six face-down cards under a full king-to-ace run
-- of thirteen, and sizing every column for that worst case would force about
-- six pixels on all of them and ruin the common case. So the steps are worked
-- out per column at paint time from what that column actually holds, and only
-- squeezed when that column needs it.
--
-- FAN_UP_MAX shows the whole corner index, rank and suit. FAN_UP_MIN still
-- shows the rank glyph, which ends at row 7 of the art. Face-down cards are
-- identical backs and carry nothing, so they are squeezed first and hardest.
local FAN_UP_MAX,   FAN_UP_MIN   = 16, 9
local FAN_DOWN_MAX, FAN_DOWN_MIN = 7, 2

-- Draw-3 spreads its three turned cards to the right, into the gap the grid
-- leaves between the waste and the foundations. 13px shows each card's corner
-- index, which is all there is to see: only the last one is playable.
local WASTE_FAN = 13

local HUD_H    = 18   -- status bar across the top
local MARGIN   = 4
local ROW_GAP  = 4    -- between the top row of piles and the tableau
local GAP_MIN, GAP_MAX = 4, 16   -- between columns
-- ---------------------------------------------------------------------------

-- Cards are drawn as fillRect runs, not as gc:drawImage, and that is measured
-- rather than left over from before the TI.Image layout was known: 53 cards at
-- 37x52 come to 721 KB once escaped into a Lua source string, 9.4x this whole
-- bundle. Klondike also repaints only on a key press, so the rects cost once
-- per keystroke and never per frame. tools/cardart.py has the full working.

-- >>> generated by tools/cardart.py -- do not edit by hand
-- Card art: "Kin Pixel Playing Cards" by KIN,
-- https://the-wild-kin.itch.io/kin-pixel-playing-cards -- see
-- assets/klondike/README.md. Regenerate with tools/cardart.py.
--
-- Each card is: the body rects in CARD_BODY, the frame rects in CARD_FRAME,
-- then run-length ink. A run is three characters -- y, x, length, each less
-- CARD_PACK -- and the runs are in row order, so drawCard can stop as soon as
-- it passes the bottom of a fanned card's visible strip.
local CARD_W, CARD_H = 37, 52
local CARD_PACK = 40
local CARD_BODY  = { 246, 243, 228 }
local CARD_FRAME = { 39, 8, 51 }
local CARD_BODY_RECTS  = { 1, 0, 35, 52, 0, 1, 1, 50, 36, 1, 1, 50 }
local CARD_FRAME_RECTS = { 1, 0, 35, 1, 0, 1, 2, 1, 35, 1, 2, 1, 0, 2, 1, 49, 36, 2, 1, 49, 1, 50, 1, 2, 35, 50, 1, 2, 2, 51, 33, 1 }
local CARD_INK = {
  { 39, 8, 51 },
  { 239, 162, 20 },
  { 255, 15, 33 },
  { 182, 162, 151 },
  { 68, 51, 128 },
}
-- Indexed (suit - 1) * 13 + rank, clubs, diamonds, hearts, spades;
-- entry 53 is the back.
local CARD_RUNS = {
  { 1, "++-,+),.*-+-.+)..*/+)/.*1,+2,+3+-4+-5-)6,+:9+;8-<7/=7/>7/?8-@5+@9+@=+A45B45C45D5+D:)D=+E:)F9+G8-MF+NG)OE-PE-QF+RF+TE*TI)UE*UI)VE-WE*WI)XE-" }, -- Clubs_ACE
  { 1, "++-,.*-+-.+*.9+/+-/9+09+1,+17*1:)1<*2,+27/3+-37*3:)3<*4+-4:)5-)59+6,+MF+N9+NG)O:)OE-P7*P:)P<*PE-Q7/QF+R7*R:)R<*RF+S9+T9+TE-U9+UH*VE-WE*XE-" }, -- Clubs_2
  { 1, "++-,.*-+-..*.9+/+-/9+09+1,+17*1:)1<*2,+27/3+-37*3:)3<*4+-4:)5-)59+6,+>9+?9+@9+A7*A:)A<*B7/C7*C:)C<*D:)E9+MF+N9+NG)O:)OE-P7*P:)P<*PE-Q7/QF+R7*R:)R<*RF+S9+T9+TE-U9+UE*VE-WE*XE-" }, -- Clubs_3
  { 1, "++*+.*,+*,.*-+-..*.3+.?+/.*/3+/?+03+0?+1,+11*14)16*1=*1@)1B*2,+21/2=/3+-31*34)36*3=*3@)3B*4+-44)4@)5-)53+5?+6,+MF+N3+N?+NG)O4)O@)OE-P1*P4)P6*P=*P@)PB*PE-Q1/Q=/QF+R1*R4)R6*R=*R@)RB*RF+S3+S?+T3+T?+TE*U3+U?+UE*VE-WE*WH*XE*XH*" }, -- Clubs_4
  { 1, "++-,+*-+-..*.3+.?+/+-/3+/?+03+0?+1,+11*14)16*1=*1@)1B*2,+21/2=/3+-31*34)36*3=*3@)3B*4+-44)4@)5-)53+5?+6,+>9+?9+@9+A7*A:)A<*B7/C7*C:)C<*D:)E9+MF+N3+N?+NG)O4)O@)OE-P1*P4)P6*P=*P@)PB*PE-Q1/Q=/QF+R1*R4)R6*R=*R@)RB*RF+S3+S?+T3+T?+TE-U3+U?+UE*VE-WH*XE-" }, -- Clubs_5
  { 1, "++-,+*-+-.+*./).3+.?+/+-/3+/?+03+0?+1,+11*14)16*1=*1@)1B*2,+21/2=/3+-31*34)36*3=*3@)3B*4+-44)4@)5-)53+5?+6,+>3+>?+?3+??+@3+@?+A1*A4)A6*A=*A@)AB*B1/B=/C1*C4)C6*C=*C@)CB*D4)D@)E3+E?+MF+N3+N?+NG)O4)O@)OE-P1*P4)P6*P=*P@)PB*PE-Q1/Q=/QF+R1*R4)R6*R=*R@)RB*RF+S3+S?+T3+T?+TE-U3+U?+UE)UH*VE-WH*XE-" }, -- Clubs_6
  { 1, "++-,.*--*.,*.3+.?+/,*/3+/?+03+0?+1,+11*14)16*1=*1@)1B*2,+21/2=/3+-31*34)36*3=*3@)3B*4+-44)4@)5-)53+5?+6,+79+89+99+:7*::):<*;7/<7*<:)<<*=:)>3+>9+>?+?3+??+@3+@?+A1*A4)A6*A=*A@)AB*B1/B=/C1*C4)C6*C=*C@)CB*D4)D@)E3+E?+MF+N3+N?+NG)O4)O@)OE-P1*P4)P6*P=*P@)PB*PE-Q1/Q=/QF+R1*R4)R6*R=*R@)RB*RF+S3+S?+T3+T?+TG*U3+U?+UG*VF*WE*XE-" }, -- Clubs_7
  { 1, "++-,+),.*-+-.+)..*.3+.?+/+-/3+/?+03+0?+1,+11*14)16*1=*1@)1B*2,+21/2=/3+-31*34)36*3=*3@)3B*4+-44)4@)5-)53+5?+6,+79+89+99+:7*::):<*;7/<7*<:)<<*=:)>3+>9+>?+?3+??+@3+@?+A1*A4)A6*A=*A@)AB*B1/B=/C1*C4)C6*C=*C@)CB*D4)D@)E3+E9+E?+F:)G7*G:)G<*H7/I7*I:)I<*J9+K9+L9+MF+N3+N?+NG)O4)O@)OE-P1*P4)P6*P=*P@)PB*PE-Q1/Q=/QF+R1*R4)R6*R=*R@)RB*RF+S3+S?+T3+T?+TE-U3+U?+UE*UI)VE-WE*WI)XE-" }, -- Clubs_8
  { 1, "++-,+),.*-+-..*.3+.?+/+-/3+/?+03+0?+1,+11*14)16*1=*1@)1B*2,+21/2=/3+-31*34)36*3=*3@)3B*4+-44)4@)5-)53+5?+6,+83+8?+93+9?+:3+:?+;1*;4);6*;=*;@);B*<1/<=/=1*=4)=6*==*=@)=B*>4)>9+>@)?3+?9+??+@9+A7*A:)A<*B7/C7*C:)C<*D3+D:)D?+E4)E9+E@)F1*F4)F6*F=*F@)FB*G1/G=/H1*H4)H6*H=*H@)HB*I3+I?+J3+J?+K3+K?+MF+N3+N?+NG)O4)O@)OE-P1*P4)P6*P=*P@)PB*PE-Q1/Q=/QF+R1*R4)R6*R=*R@)RB*RF+S3+S?+T3+T?+TE-U3+U?+UE*VE-WE*WI)XE-" }, -- Clubs_9
  { 1, "++)+-+,+),-),/)-+)--)-/).+).-)./).3+.?+/+)/-+/3+/?+03+0?+1,+11*14)16*1=*1@)1B*2,+21/2=/3+-31*34)36*3=*3@)3B*4+-44)4@)5-)53+59+5?+6,+69+79+87*8:)8<*97/:3+:7*::):<*:?+;3+;:);?+<3+<9+<?+=1*=4)=6*==*=@)=B*>1/>=/?1*?4)?6*?=*?@)?B*@4)@@)A3+A?+C3+C?+D4)D@)E1*E4)E6*E=*E@)EB*F1/F=/G1*G4)G6*G=*G@)GB*H3+H9+H?+I3+I:)I?+J3+J7*J:)J<*J?+K7/L7*L:)L<*M9+MF+N3+N9+N?+NG)O4)O9+O@)OE-P1*P4)P6*P=*P@)PB*PE-Q1/Q=/QF+R1*R4)R6*R=*R@)RB*RF+S3+S?+T3+T?+TE+TI)U3+U?+UE)UG)UI)VE)VG)VI)WE)WG)WI)XE+XI)" }, -- Clubs_10
  { 1, "+.*,.*,19,D),F*-.*-C*-G)..*.9*.=).C*.G)/+-/6*/;)/>)/C*/G)04)08)0;)0>)0C*0G)1,+14)18)1;)1=)1G)2,+2412G)3+-36*3<)3C*3G)4+-4G)5-)5G)6,+6C*6G)78)7<)7G)8-)83)88-8G)9-)92)94-9<+9C*9G):-):1):8-:?):G);-);0);8);:);<);@);G)<-)</)<8)<:)<<)<A-<G)=-*=8)=:)=<)=B)=E)=G)>-)>8)>:)><)>B)>E)>G)?-)?88@-8@A,@G)A-)A1,A97B-8BA+BG)C-)C0-C97D-6DG)E-)E/)E2)E9*EG)F-)F/)F2)FF*G-)G/-G9*GE)GG)H-)H4)H8)H;)HD)HG)I-)I5)I8-IC)IG)J-)J0*J6+J<-JB)JG)K-)K8-KA)KG)L-)L8)L<)M-)M0*MF+N-)NG)O-)OE-P-)P0*P8)P=*PE-Q-)Q81QF+R-)R7)R9)R<)R@)RF+S-)S0*S6)S9)S<)S@)T-)T0*T6)T9)T=*TE-U-)U0*U7)U:*UE*V-)V0*VE*W-*W0)W39WE*XE*", 2, "1C*2C*38)45+4<)4C*55+5<*5C*64,6<*74,7=*7C*84,8=*8C*:C*;9);;);C*<0+<9)<;)=3)=9)=;)=A)>3)>9)>;)>A)?3)DA)E3)EA)F3)F9*FA)GB+H0*H9*I0*K0*K6*K=,L0*L6*L=,M7*M=,N0*N7*N=+O0*O8)O=+P<)Q0*R0*", 3, ".;*/5)/8+/<*05+09*0<*15+19*1<):2*;1.;>*<3,<>+=/,=4+=>+>.->4+>>+?.-?4+D;*D>+DB-E4+E8)E;*E>+EB-F4+F8)F;*F>+FB,G4+G8)G;*G>,H5*H<)H>.IA*R8)R:*R=+S7*S:*S=+T7*T:+T?)U8*" }, -- Clubs_J
  { 1, "++,,+*,.),1?-+*-.)-G).+,.5).G)/+-/6)/G)07)0:*0G)1,+18)1B*1G)2,+22)28,2>,2G)3+-31+37/3@)3G)4+-41+48*4;*4>+4G)5-)52)58)5<)5A)5G)6,+61+67*6<)6A)6G)72)77*7<)7B)7G)8-)80,86,8=)8C)8G)9-)90)93)96+9=*9D)9G):-):0):3):53:E):G);-);0);3-;:);=,;F*<-)<06<A)<G)=-)=2)=6*=:)==)=B)=G)>-)>0*>6*>:)>=)>C)>F*?-+?6*?:6@-8@A,@G)A-)A1,A97B-8BA+BG)C-)C0-C97D-6D=*DE+E-*E1)E7)E:)E=*EC*EG)F-)F2)F7)F:)F=*FB)FG)G-)G3)G76GG)H-*H4,H:)H=-HD)HG)I-)I/)I53IA)ID)IG)J-)J0)J6*J<+JA)JD)JG)K-)K1)K7)K;,KA,KG)L-)L2)L8)L<*LB)M-)M3)M8)M<*MA+MF+N-)N3)N8)N<)NB)NG)O-)O4+O8*O;*OA+OE-P-)P4)P7/PA+PE-Q-)Q3,Q9,QB)QF+R-)R1*R<)RF+S-)S9*S=)T-)T>)TE-U-)U?)UF,V-)VF)VH*W-?WF)WH*XF,", 2, ".61/730<019+1>,2<*3>*6?*7?*8<)99,9B*:B*;E)<E*=8*=;*>8*>;*?8*D;*E8*E;*F8*F;*G.*H/)I1*J1*J8,K8)L4*M4*P5*Q7*R3,R9+S10T33U61", 3, "08*1<*5>+6>)7>)7A)8?,9@*:A):D);B+<>+<C*=3+=>,=D+>2,>>-?0.D?.E2-E?,F.+F3,F?+G0*G4+H0+I0)I3)J3*K2,L3)L6)M6)N4+R7*S;*" }, -- Clubs_Q
  { 1, "++*+.*,+-,18,E+-+,-G).+*..*.G)/+*/.*/4)/8)/>)/G)04)07)09)0>)0G)1,+15)17)19)1;)1=*1G)2,+26/2G)3+-3G)4+-4G)5-)55)57)59*5<)5G)6,+65+69,6G)7G)8-)8?*8G)9-)93)98)9A)9G):-):2*:7,:A):G);-);1,;7,;=);@.;G)<-)<0-<7)<:)<=)<?/<G)=-)=/)=7,==)=?)=A)=D)=G)>-*>7)>:)>=)>?)>A)>D)>G)?-)?7)?:0?D,@-8@A,@G)A-)A1,A97B-8BA+BG)C-)C0-C97D-,D30D=)DG)E-)E0)E3)E5)E7)E:)E=)EF*F-)F0)F3)F5)F7)F:,FE)FG)G-)G//G7)G:)G=)G@-GG)H-)H/.H7)H:,H@,HG)I-)I3)I:,IA*IG)J-)J3)J<)JA)JG)K-)K4*KG)L-)M-)M8,M=+MF+N-)N8)N:*N=)N?)NG)O-)OE-P-)PE-Q-)Q8/QF+R-)R6*R9)R;)R=)R?*RF+S-)S6)S;)S=)S@)T-)T6)T<)T@)TE*TH*U-)UE*UH*V-)VF,W-+W48WE-XE*XH*", 4, ",C)-B*.B*/B*0B*1B*2B*3B*4B*5B*6B*7B*8B*9B*:B*I1*J1*K1*L1*M1*N1*O1*P1*Q1*R1*S1*T1*U1*V1*W1)", 2, ".5*.8*.;+/5+/9-05*0:,36)3;*46)4;+56)5;)5=)6=)75*78)7;,84394,99-9?*:>+;>*<>)=>)>>)E6)F6)G6)H5*I4+J4*J8,J=,K63L6,L<)L>*M7)N7)N9)N>)O7+O>)P8*P>)S7,S>*T7-T=+U7+U;*U>*", 3, "08)16)18)1:)1<)<8*=0-=@)>/.>8*>@)?./?8*D;*D@/E4)E;*E@.F4)F@-G;*R8)R:)R<)R>)S<)" }, -- Clubs_K
  { 3, ",,--,)-/*.,-/,)//*0,)0/*2.)3-+4,-5,-6-+7.)<:)=9+>8-?7/@61A53B53C61D7/E8-F9+G:)LF)ME+ND-OD-PE+QF)SD*SH)TD*TH)UD-VD*VH)WD-" }, -- Diamonds_ACE
  { 3, "++-,.*-+-.+*.:)/+-/9+08-1-)17/2,+27/3+-38-4+-49+5,+5:)6-)MG)N:)NF+O9+OE-P8-PE-Q7/QF+R7/RG)S8-T9+TE-U:)UH*VE-WE*XE-" }, -- Diamonds_2
  { 3, "++-,.*-+-..*.:)/+-/9+08-1-)17/2,+27/3+-38-4+-49+5,+5:)6-)>:)?9+@8-A7/B7/C8-D9+E:)MG)N:)NF+O9+OE-P8-PE-Q7/QF+R7/RG)S8-T9+TE-U:)UE*VE-WE*XE-" }, -- Diamonds_3
  { 3, "++*+.*,+*,.*-+-..*.4).@)/.*/3+/?+02-0>-1-)11/1=/2,+21/2=/3+-32-3>-4+-43+4?+5,+54)5@)6-)MG)N4)N@)NF+O3+O?+OE-P2-P>-PE-Q1/Q=/QF+R1/R=/RG)S2-S>-T3+T?+TE*U4)U@)UE*VE-WE*WH*XE*XH*" }, -- Diamonds_4
  { 3, "++-,+*-+-..*.4).@)/+-/3+/?+02-0>-1-)11/1=/2,+21/2=/3+-32-3>-4+-43+4?+5,+54)5@)6-)>:)?9+@8-A7/B7/C8-D9+E:)MG)N4)N@)NF+O3+O?+OE-P2-P>-PE-Q1/Q=/QF+R1/R=/RG)S2-S>-T3+T?+TE-U4)U@)UE*VE-WH*XE-" }, -- Diamonds_5
  { 3, "++-,+*-+-.+*./).4).@)/+-/3+/?+02-0>-1-)11/1=/2,+21/2=/3+-32-3>-4+-43+4?+5,+54)5@)6-)>4)>@)?3+??+@2-@>-A1/A=/B1/B=/C2-C>-D3+D?+E4)E@)MG)N4)N@)NF+O3+O?+OE-P2-P>-PE-Q1/Q=/QF+R1/R=/RG)S2-S>-T3+T?+TE-U4)U@)UE)UH*VE-WH*XE-" }, -- Diamonds_6
  { 3, "++-,.*--*.,*.4).@)/,*/3+/?+02-0>-1-)11/1=/2,+21/2=/3+-32-3>-4+-43+4?+5,+54)5@)6-)7:)89+98-:7/;7/<8-=9+>4)>:)>@)?3+??+@2-@>-A1/A=/B1/B=/C2-C>-D3+D?+E4)E@)MG)N4)N@)NF+O3+O?+OE-P2-P>-PE-Q1/Q=/QF+R1/R=/RG)S2-S>-T3+T?+TG*U4)U@)UG*VF*WE*XE-" }, -- Diamonds_7
  { 3, "++-,+),.*-+-.+)..*.4).@)/+-/3+/?+02-0>-1-)11/1=/2,+21/2=/3+-32-3>-4+-43+4?+5,+54)5@)6-)7:)89+98-:7/;7/<8-=9+>4)>:)>@)?3+??+@2-@>-A1/A=/B1/B=/C2-C>-D3+D?+E4)E:)E@)F9+G8-H7/I7/J8-K9+L:)MG)N4)N@)NF+O3+O?+OE-P2-P>-PE-Q1/Q=/QF+R1/R=/RG)S2-S>-T3+T?+TE-U4)U@)UE*UI)VE-WE*WI)XE-" }, -- Diamonds_8
  { 3, "++-,+),.*-+-..*.4).@)/+-/3+/?+02-0>-1-)11/1=/2,+21/2=/3+-32-3>-4+-43+4?+5,+54)5@)6-)84)8@)93+9?+:2-:>-;1/;=/<1/<=/=2-=>->3+>:)>?+?4)?9+?@)@8-A7/B7/C8-D4)D9+D@)E3+E:)E?+F2-F>-G1/G=/H1/H=/I2-I>-J3+J?+K4)K@)MG)N4)N@)NF+O3+O?+OE-P2-P>-PE-Q1/Q=/QF+R1/R=/RG)S2-S>-T3+T?+TE-U4)U@)UE*VE-WE*WI)XE-" }, -- Diamonds_9
  { 3, "++)+-+,+),-),/)-+)--)-/).+).-)./).4).@)/+)/-+/3+/?+02-0>-1-)11/1=/2,+21/2=/3+-32-3>-4+-43+4?+5,+54)5:)5@)6-)69+78-87/97/:4):8-:@);3+;9+;?+<2-<:)<>-=1/==/>1/>=/?2-?>-@3+@?+A4)A@)C4)C@)D3+D?+E2-E>-F1/F=/G1/G=/H2-H:)H>-I3+I9+I?+J4)J8-J@)K7/L7/M8-MG)N4)N9+N@)NF+O3+O:)O?+OE-P2-P>-PE-Q1/Q=/QF+R1/R=/RG)S2-S>-T3+T?+TE+TI)U4)U@)UE)UG)UI)VE)VG)VI)WE)WG)WI)XE+XI)" }, -- Diamonds_10
  { 1, ",19,D),F*-C*-G).9*.=).C*.G)/6*/;)/>)/C*/G)04)08)0;)0>)0C*0G)14)18)1;)1=)1G)2412G)36*3<)3C*3G)4G)5G)6C*6G)78)7<)7G)8-)83)88-8G)9-)92)94-9<+9C*9G):-):1):8-:?):G);-);0);8);:);<);@);G)<-)</)<8)<:)<<)<A-<G)=-*=8)=:)=<)=B)=E)=G)>-)>8)>:)><)>B)>E)>G)?-*?8)?:6@-6@G)A-)AG)B-)BG)C-)C:6D-5D<*DA*DF*E-)E/)E2)E9*EG)F-)F/)F2)FF*G-)G/-G9*GE)GG)H-)H4)H8)H;)HD)HG)I-)I5)I8-IC)IG)J-)J0*J6+J<-JB)JG)K-)K8-KA)KG)L-)L8)L<)M-)M0*N-)O-)P-)P0*P8)P=*Q-)Q81R-)R7)R9)R<)R@)S-)S0*S6)S9)S<)S@)T-)T0*T6)T9)T=*U-)U0*U7)U:*V-)V0*W-*W0)W39", 2, "1C*2C*38)45+4<)4C*55+5<*5C*64,6<*74,7=*7C*84,8=*8C*:C*;9);;);C*<0+<9)<;)=3)=9)=;)=A)>3)>9)>;)>A)?3)?9)E3)EA)F3)F9*FA)GB+H0*H9*I0*K0*K6*K=,L0*L6*L=,M7*M=,N0*N7*N=+O0*O8)O=+P<)Q0*R0*", 3, "+.*,.*-.*..*.;*/+-/5)/8+/<*05+09*0<*1-)15+19*1<)2,+3+-4+-5,+6-):2*;1.;>*<3,<>+=/,=4+=>+>.->4+>>+?/,?4+@<*@?*@B*@E*A.)A3*A9*A?*AE*B0*B6*B<*BB*C.)C0*C3*C6*C9)D:*D>+DC+E4+E8)E;*E>+EB-F4+F8)F;*F>+FB,G4+G8)G;*G>,H5*H<)H>.IA*MG)NF+OE-PE-QF+R8)R:*R=+RG)S7*S:*S=+T7*T:+T?)TE-U8*UE*VE*WE*XE*" }, -- Diamonds_J
  { 1, ",1?-G).5).G)/6)/G)07)0C)0G)18)1B*1G)28,2@*2G)38.3@)3G)47*4;*4>+4G)57*5<*5@)5G)62)67*6=*6A)6G)72)76+7<,7B)7G)8-)80,86*89,8>)8@)8C)8G)9-)90)93)96)9;)9>*9A)9D)9G):-):0):3):5*:>*:B):E):G);-);0);3-;=,;C);F*<-)<0.<73<D)<G)=-)=2+=8*==*=B)=E)=G)>-)>0*>3*>8*>=*>C)>F*?-+?3*?8*?;5@-6@G)A-)AG)B-)BG)C-)C:6D-5D;*D@*DE+E-*E1)E6*E;*E@*EC*EG)F-)F/)F2)F6*F;*F@+FG)G-)G0)G33G?.GG)H-*H1)H4,H=-HD)HG)I-)I/)I2)I5*I>*IA)ID)IG)J-)J0)J3)J5*J9)J>)JA)JD)JG)K-)K1)K4)K6)K8,K=*KA,KG)L-)L2)L5,L<+LB)M-)M3)M6*M<*MB)N-)N3*N7*N<*O-)O4+O8*O<*P-)P4)P7/Q-)Q3*Q9,R-)R1*R<)S-)S1)S=)T-)T>)U-)U?)V-)W-?", 2, ".61/7*/:00</1>,69,79+8?)9@):@*;A*<B*=C*>D*E/*F0*G1*H2*I3*J4)K5)L9+M8,R3,S2/T30T<*U61", 3, "++,,+*,.)-+*-.).+,/+-/9)09*1-)19*1<)2,+22)2<)2>)3+-31+3>)4+-41+4=)5,+52)5>*6-)6?*7@*8=)8A*97)99)9=)9B*:7):9):;):=):C*;9);;);D*<6)<E*=5+=:+=?+=F)>2)>5+>:+>?,?0+?5+?:)@<*@?*@B*@E*A.)A0*A3*A9*A?*AE*B0*B6*B<*BB*C.)C3*C6*C9)D:)D=+DB+E2,E8+E=+EB)F.)F3+F8+F=+G.*G>)H/*H9)H;)I0*I7)I9)I;)I=)J1*J7)J;)J=)K2*K7)L3*M4*MG)N5*NB)NF+O7)OA+OE-P6)PA+PE-Q6)Q8)QB)QF+R8)R:*RG)S:*T;)TE-UF,VF)VH*WF)WH*XF," }, -- Diamonds_Q
  { 1, ",1?-G).G)/4)/6)/>)/G)04*07)0>)0A)0G)15)17)19)1>)1A)1G)26,2;)2=)2B)2G)36)3:,3C)3G)45)4B)4G)55*5A)5G)66)6A)6G)7G)8-)8?*8G)9-)92*9>)9A)9G):-):2):42:A):G);-);1*;@-;G)<-)<0,<?/<G)=-)=/)=25=A*=E)=G)>-*>2*>7*><*>A*>E)>G)?-*?2*?7*?;0?E+@-6@B+@G)A-)AG)B-)BG)C-)C0+C:6D-+D20D<*DA*DF*E-)E/)E2*E7*E<*EA*EF*F-)F/)F2*F65FE)FG)G-)G//GA,GG)H-)H0-HB*HG)I-)I3)I72IB)IG)J-)J3)J6)JA*JG)K-)K4*KG)L-)M-)M3)M>)N-)N3)N>*O-)O2)O?)P-)P1)P7,P>)Q-)Q2)Q7)Q9)Q;,R-)R3)R6)R;)R=)R?)S-)S3)S6)S=)S?*T-)T6)T>)T@)U-)V-)W-?", 4, "1@)2?+3?,4?+5@)N4)O3+P2,Q3+R4)", 2, ".5+.9*.<*/5)/7//C*08.0C*1:,1C*2C*3D)4:,4C*5;,5C*67*6;,6C*75*7:-7C*83+88/8C*9429C*:C*I0*J0*J72K0*K6/K?+L0*L6.L>*M0*M6,M<*N0*N6,O0*O7,P0)Q0*R0*R7,S0*S7.T0*T7/T?)U7*U:*U=+", 3, "++*+.*,+--+,.+*..*/+*/.*06)1-)16)18)2,+2:)2<)3+-4+-5,+6-)9@):>):@);4);6);8);:);<);>)<4)<6)<8)<:)<<)<>)=0*=?*>/+>4+>9+>>+?/+?4+?9*@<*@?*@E*A.)A3*A9*A?*AE*B0*B6*B<*BB*C.)C3*C6*C9)D:*D>+DC+E4+E9+E>+EC+F4*FC*G6)G8)G:)G<)G>)G@)H6)H8)H:)H<)H>)H@)I4)I6)J4)MG)NF+OE-PE-Q8)Q:)QF+R<)R>)RG)S>)TE*TH*UE*UH*VF,WE-XE*XH*" }, -- Diamonds_K
  { 3, "++-,+),.*-+-.+)..*/+)/.*2+*2.*3+-4+-5,+6-)=6+=<+>5->;-?53@53A53B53C61D7/E8-F9+G:)MG)NF+OE-PE-QE*QH*TE*TI)UE*UI)VE-WE*WI)XE-" }, -- Hearts_ACE
  { 3, "++-,.*-+-.+*.8*.;*/+-/7/07/17/2+*2.*27/3+-38-4+-49+5,+5:)6-)MG)N:)NF+O9+OE-P8-PE-Q7/QE*QH*R7/S7/T7/TE-U8*U;*UH*VE-WE*XE-" }, -- Hearts_2
  { 3, "++-,.*-+-..*.8*.;*/+-/7/07/17/2+*2.*27/3+-38-4+-49+5,+5:)6-)>8*>;*?7/@7/A7/B7/C8-D9+E:)MG)N:)NF+O9+OE-P8-PE-Q7/QE*QH*R7/S7/T7/TE-U8*U;*UE*VE-WE*XE-" }, -- Hearts_3
  { 3, "++*+.*,+*,.*-+-..*.2*.5*.>*.A*/.*/1//=/01/0=/11/1=/2+*2.*21/2=/3+-32-3>-4+-43+4?+5,+54)5@)6-)MG)N4)N@)NF+O3+O?+OE-P2-P>-PE-Q1/Q=/QE*QH*R1/R=/S1/S=/T1/T=/TE*U2*U5*U>*UA*UE*VE-WE*WH*XE*XH*" }, -- Hearts_4
  { 3, "++-,+*-+-..*.2*.5*.>*.A*/+-/1//=/01/0=/11/1=/2+*2.*21/2=/3+-32-3>-4+-43+4?+5,+54)5@)6-)>8*>;*?7/@7/A7/B7/C8-D9+E:)MG)N4)N@)NF+O3+O?+OE-P2-P>-PE-Q1/Q=/QE*QH*R1/R=/S1/S=/T1/T=/TE-U2*U5*U>*UA*UE*VE-WH*XE-" }, -- Hearts_5
  { 3, "++-,+*-+-.+*./).2*.5*.>*.A*/+-/1//=/01/0=/11/1=/2+*2.*21/2=/3+-32-3>-4+-43+4?+5,+54)5@)6-)>2*>5*>>*>A*?1/?=/@1/@=/A1/A=/B1/B=/C2-C>-D3+D?+E4)E@)MG)N4)N@)NF+O3+O?+OE-P2-P>-PE-Q1/Q=/QE*QH*R1/R=/S1/S=/T1/T=/TE-U2*U5*U>*UA*UE)UH*VE-WH*XE-" }, -- Hearts_6
  { 3, "++-,.*--*.,*.2*.5*.>*.A*/,*/1//=/01/0=/11/1=/2+*2.*21/2=/3+-32-3>-4+-43+4?+5,+54)5@)6-)78*7;*87/97/:7/;7/<8-=9+>2*>5*>:)>>*>A*?1/?=/@1/@=/A1/A=/B1/B=/C2-C>-D3+D?+E4)E@)MG)N4)N@)NF+O3+O?+OE-P2-P>-PE-Q1/Q=/QE*QH*R1/R=/S1/S=/T1/T=/TG*U2*U5*U>*UA*UG*VF*WE*XE-" }, -- Hearts_7
  { 3, "++-,+),.*-+-.+)..*.2*.5*.>*.A*/+-/1//=/01/0=/11/1=/2+*2.*21/2=/3+-32-3>-4+-43+4?+5,+54)5@)6-)78*7;*87/97/:7/;7/<8-=9+>2*>5*>:)>>*>A*?1/?=/@1/@=/A1/A=/B1/B=/C2-C>-D3+D?+E4)E:)E@)F9+G8-H7/I7/J7/K7/L8*L;*MG)N4)N@)NF+O3+O?+OE-P2-P>-PE-Q1/Q=/QE*QH*R1/R=/S1/S=/T1/T=/TE-U2*U5*U>*UA*UE*UI)VE-WE*WI)XE-" }, -- Hearts_8
  { 3, "++-,+),.*-+-..*.2*.5*.>*.A*/+-/1//=/01/0=/11/1=/2+*2.*21/2=/3+-32-3>-4+-43+4?+5,+54)5@)6-)82*85*8>*8A*91/9=/:1/:=/;1/;=/<1/<=/=2-=>->3+>8*>;*>?+?4)?7/?@)@7/A7/B7/C8-D4)D9+D@)E3+E:)E?+F2-F>-G1/G=/H1/H=/I1/I=/J1/J=/K2*K5*K>*KA*MG)N4)N@)NF+O3+O?+OE-P2-P>-PE-Q1/Q=/QE*QH*R1/R=/S1/S=/T1/T=/TE-U2*U5*U>*UA*UE*VE-WE*WI)XE-" }, -- Hearts_9
  { 3, "++)+-+,+),-),/)-+)--)-/).+).-)./).2*.5*.>*.A*/+)/-+/1//=/01/0=/11/1=/2+*2.*21/2=/3+-32-38*3;*3>-4+-43+47/4?+5,+54)57/5@)6-)67/77/88-99+:2*:5*::):>*:A*;1/;=/<1/<=/=1/==/>1/>=/?2-?>-@3+@?+A4)A@)C4)C@)D3+D?+E2-E>-F1/F=/G1/G=/H1/H=/I1/I:)I=/J2*J5*J9+J>*JA*K8-L7/M7/MG)N4)N7/N@)NF+O3+O7/O?+OE-P2-P8*P;*P>-PE-Q1/Q=/QE*QH*R1/R=/S1/S=/T1/T=/TE+TI)U2*U5*U>*UA*UE)UG)UI)VE)VG)VI)WE)WG)WI)XE+XI)" }, -- Hearts_10
  { 1, ",19,D),F*-C*-G).9*.=).C*.G)/6*/;)/>)/C*/G)04)08)0;)0>)0C*0G)14)18)1;)1=)1G)2412G)36*3<)3C*3G)4G)5G)6C*6G)78)7<)7G)8-)83)88-8G)9-)92)94-9<+9C*9G):-):1):8-:?):G);-);0);8);:);<);@);G)<-)</)<8)<:)<<)<A-<G)=-*=8)=:)=<)=B)=E)=G)>-)>8)>:)><)>B)>E)>G)?-*?8)?:6@-6@G)A-)AG)B-)BG)C-)C:6D-6D<*DA*DF*E-)E/)E2)E9*EG)F-)F/)F2)FF*G-)G/-G9*GE)GG)H-)H4)H8)H;)HD)HG)I-)I5)I8-IC)IG)J-)J0*J6+J<-JB)JG)K-)K8-KA)KG)L-)L8)L<)M-)M0*N-)O-)P-)P0*P8)P=*Q-)Q81R-)R7)R9)R<)R@)S-)S0*S6)S9)S<)S@)T-)T0*T6)T9)T=*U-)U0*U7)U:*V-)V0*W-*W0)W39", 2, "1C*2C*38)45+4<)4C*55+5<*5C*64,6<*74,7=*7C*84,8=*8C*:C*;9);;);C*<0+<9)<;)=3)=9)=;)=A)>3)>9)>;)>A)?3)?9)E3)EA)F3)F9*FA)GB+H0*H9*I0*K0*K6*K=,L0*L6*L=,M7*M=,N0*N7*N=+O0*O8)O=+P<)Q0*R0*", 3, "+.*,.*-.*..*.;*/+-/5)/8+/<*05+09*0<*15+19*1<)2+*2.*3+-4+-5,+6-):2*;1.;>*<3,<>+=/,=4+=>+>.->4+>>+?/,?4+@;*@?*@C*A.*A2*A6*A:5B.5B=*BA*BE*C0*C4*C8*D;)D>+DC+E4+E8)E;*E>+EB-F4+F8)F;*F>+FB,G4+G8)G;*G>,H5*H<)H>.IA*MG)NF+OE-PE-QE*QH*R8)R:*R=+S7*S:*S=+T7*T:+T?)TE-U8*UE*VE*WE*XE*" }, -- Hearts_J
  { 1, ",1?-G).3).G)/4)/G)05)0G)16)1@*1G)26,2>*2G)35/3>)3G)45*49*4<+4G)56)5:)5?)5G)65*6:)6?)6G)75*7:)7@)7D)7G)8-)84,8;)8A)8D)8G)9-)94+9;*9B,9G):-):33:B):E):G);-);2);6);8);:);>);B);E);G)<-)<1)<6)<8)<:)<?)<B)<E)<G)=-)=0)=6)=8)=:)=@)=B.>-+>6)>8)>:)>A)>G)?-)?6)?8)?:6@-6@G)A-)AG)B-)BG)C-)C:6D-6D<)D>)DG)E-)E3)E:)E<)EE+F-.F4)F:)F<)FD)FG)G-)G/)G2)G5)G:)G<)GC)GG)H-)H/)H2)H6*H:)H<)H>)HB)HG)I-)I/)I2)I73IG)J-)J/,J8*J>+JG)K-)K0)K3)K9)K=,KG)L-)L0)L4)L:)L>*M-)M5)M:)M>*N-)N5)N:)N>)O-)O6+O:*O>*P-)P6)P9/Q-)Q5,Q;,R-)R3*R>)S-)S;*S?)T-)T@)U-)UA)V-)W-?", 2, ".41/5*/9/0:01<,8:)97,;5);;)<5)<;)=5)=;)>5)>;.?.0D?0E4.EB)F9)G9)G@)H9)J:,K:)P7*Q9*R5,R;+S30T53U81", 3, "++,,+*,.)-+*-.).+,/+-/7*06,17*1:*2+*2.*2<*3+-3C)3E)4+-4C+5,+5<+5C+6-)6<)6>)6D)7<,8=*8@)9>,:?*;3*;<*;@*<2+<<+<A)=1,=<,>0->D+@;*@?*@C*A.*A2*A6*A:5B.5B=*BA*BE*C0*C4*C8*E.+E>,EC*F5,F>.G3)G6+G>*GA*H3*H8)H?+I4*J3,K4)K6*L5,M0)M6)M8)MG)N/+N6+NF+O/+OE-P/)P1)PE-QE*QH*R9*S=*TE-UF,VF)VH*WF)WH*XF," }, -- Hearts_Q
  { 1, ",1?-G).G)/4)/8)/>)/@*/G)04)07)09)0>)0@*0G)15+1951G)2602?+2E)2G)3=)3?+3E)3G)4>04G)5?+5D*5G)66*69*6?-6E)6G)76)7:)7A)7D*7G)8-)8?-8F*9-)93)98)9>)9A)9F*:-):2*:7,:>):A):G);-);1,;7,;=);@);G)<-)<0.<7)<:)<=)<@)<G)=-)=/)=2*=6-==,=G)>-*>1)>3)>7)>:)>=)>@)>G)?-)?1)?3)?7)?:6@-6@G)A-)AG)B-)BG)C-)C:6D-6D=)DA)DC)DG)E-)E4)E7)E:)E=)EA)EC)EF*F-)F4,F:-FA*FE)FG)G-)G4)G7)G:)G=)G?.GG)H-)H4)H7)H:,H@,HG)I-)I3)I6)I:,IA*IG)J-*J3)J6)J<)JA)JG)K-*K1-KG)L-)L/*L3)L:)L>)M-)M/)M1-M:*M=*N-)N/*N3+O-)O/0P-)P/)P3+P7)Q-)Q/)Q3+Q70R-)R/5R=+S-)S3*S6)S;)S=)S@)T-)T3*T6)T<)T@)U-)V-)W-?", 4, "2>)3>)P6)Q6)", 2, ".5*.8*.;+/5+/9-05*0:,36*39,46)4;+55*5;+65)6;+6D)75)77+7;,7B*84394,99-9?*:?*;>*<8*<>*>2)>8*>>*?2)?8*D;*DB)E5*E;*EB)G5*G;*H5*I4*J4*J7-J=,K63L1*L6,L;+L?)M0)M7+M?)N7+N>*O7+O>)P8,P=*S7,S>*T7-T=+U7+U;*U>*", 3, "++*+.*,+--+,.+*..*/+*/.*08)18)2+*2.*3+-4+-5,+6-)8D*9B,:4+:;+:B-;5*;;*;A.<6)<;*<A.=0*=;*=A.>/*>;*>A.?.+@;*@?*@C*A.*A2*A6*A:5B.5B=*BA*BE*C0*C4*C8*DD+E..E8*ED*F..F8*FC*G..G8*G>)H..H8*H>*I.-I7+I>+J/,K/*MG)NF+OE-PE-QE*QH*R<)S<)TE*TH*UE*UH*VF,WE-XE*XH*" }, -- Hearts_K
  { 1, "++-,+),.*-+-.+)..*/+)/.*1-)2,+3+-4+-5-)6,+9:)::);9+<8-=7/>61?53@45A37B37C37D37E45F5,F:)F<,G:)H9+I8-MF+NG)OE-PE-QF+RG)TE*TI)UE*UI)VE-WE*WI)XE-" }, -- Spades_ACE
  { 1, "++-,.*-+-.+*.:)/+-/9+08-1-)17/2,+27/3+-38-4+-4:)5-)59+6,+MF+N9+NG)O:)OE-P8-PE-Q7/QF+R7/RG)S8-T9+TE-U:)UH*VE-WE*XE-" }, -- Spades_2
  { 1, "++-,.*-+-..*.:)/+-/9+08-1-)17/2,+27/3+-38-4+-4:)5-)59+6,+>:)?9+@8-A7/B7/C8-D:)E9+MF+N9+NG)O:)OE-P8-PE-Q7/QF+R7/RG)S8-T9+TE-U:)UE*VE-WE*XE-" }, -- Spades_3
  { 1, "++*+.*,+*,.*-+-..*.4).@)/.*/3+/?+02-0>-1-)11/1=/2,+21/2=/3+-32-3>-4+-44)4@)5-)53+5?+6,+MF+N3+N?+NG)O4)O@)OE-P2-P>-PE-Q1/Q=/QF+R1/R=/RG)S2-S>-T3+T?+TE*U4)U@)UE*VE-WE*WH*XE*XH*" }, -- Spades_4
  { 1, "++-,+*-+-..*.4).@)/+-/3+/?+02-0>-1-)11/1=/2,+21/2=/3+-32-3>-4+-44)4@)5-)53+5?+6,+>:)?9+@8-A7/B7/C8-D:)E9+MF+N3+N?+NG)O4)O@)OE-P2-P>-PE-Q1/Q=/QF+R1/R=/RG)S2-S>-T3+T?+TE-U4)U@)UE*VE-WH*XE-" }, -- Spades_5
  { 1, "++-,+*-+-.+*./).4).@)/+-/3+/?+02-0>-1-)11/1=/2,+21/2=/3+-32-3>-4+-44)4@)5-)53+5?+6,+>4)>@)?3+??+@2-@>-A1/A=/B1/B=/C2-C>-D4)D@)E3+E?+MF+N3+N?+NG)O4)O@)OE-P2-P>-PE-Q1/Q=/QF+R1/R=/RG)S2-S>-T3+T?+TE-U4)U@)UE)UH*VE-WH*XE-" }, -- Spades_6
  { 1, "++-,.*--*.,*.4).@)/,*/3+/?+02-0>-1-)11/1=/2,+21/2=/3+-32-3>-4+-44)4@)5-)53+5?+6,+7:)89+98-:7/;7/<8-=:)>4)>9+>@)?3+??+@2-@>-A1/A=/B1/B=/C2-C>-D4)D@)E3+E?+MF+N3+N?+NG)O4)O@)OE-P2-P>-PE-Q1/Q=/QF+R1/R=/RG)S2-S>-T3+T?+TG*U4)U@)UG*VF*WE*XE-" }, -- Spades_7
  { 1, "++-,+),.*-+-.+)..*.4).@)/+-/3+/?+02-0>-1-)11/1=/2,+21/2=/3+-32-3>-4+-44)4@)5-)53+5?+6,+7:)89+98-:7/;7/<8-=:)>4)>9+>@)?3+??+@2-@>-A1/A=/B1/B=/C2-C>-D4)D@)E3+E9+E?+F:)G8-H7/I7/J8-K9+L:)MF+N3+N?+NG)O4)O@)OE-P2-P>-PE-Q1/Q=/QF+R1/R=/RG)S2-S>-T3+T?+TE-U4)U@)UE*UI)VE-WE*WI)XE-" }, -- Spades_8
  { 1, "++-,+),.*-+-..*.4).@)/+-/3+/?+02-0>-1-)11/1=/2,+21/2=/3+-32-3>-4+-44)4@)5-)53+5?+6,+84)8@)93+9?+:2-:>-;1/;=/<1/<=/=2-=>->4)>:)>@)?3+?9+??+@8-A7/B7/C8-D3+D:)D?+E4)E9+E@)F2-F>-G1/G=/H1/H=/I2-I>-J3+J?+K4)K@)MF+N3+N?+NG)O4)O@)OE-P2-P>-PE-Q1/Q=/QF+R1/R=/RG)S2-S>-T3+T?+TE-U4)U@)UE*VE-WE*WI)XE-" }, -- Spades_9
  { 1, "++)+-+,+),-),/)-+)--)-/).+).-)./).4).@)/+)/-+/3+/?+02-0>-1-)11/1=/2,+21/2=/3+-32-3>-4+-44)4@)5-)53+5:)5?+6,+69+78-87/97/:4):8-:@);3+;:);?+<2-<9+<>-=1/==/>1/>=/?2-?>-@4)@@)A3+A?+C3+C?+D4)D@)E2-E>-F1/F=/G1/G=/H2-H9+H>-I3+I:)I?+J4)J8-J@)K7/L7/M8-MF+N3+N9+N?+NG)O4)O:)O@)OE-P2-P>-PE-Q1/Q=/QF+R1/R=/RG)S2-S>-T3+T?+TE+TI)U4)U@)UE)UG)UI)VE)VG)VI)WE)WG)WI)XE+XI)" }, -- Spades_10
  { 1, "+.*,.*,19,D),F*-.*-C*-G)..*.9*.=).C*.G)/+-/6*/;)/>)/C*/G)04)08)0;)0>)0C*0G)1-)14)18)1;)1=)1G)2,+2412G)3+-36*3<)3C*3G)4+-4G)5-)5G)6,+6C*6G)78)7<)7G)8-)83)88-8G)9-)92)94-9<+9C*9G):-):1):8-:?):G);-);0);8);:);<);@);G)<-)</)<8)<:)<<)<A-<G)=-*=8)=:)=<)=B)=E)=G)>-)>8)>:)><)>B)>E)>G)?-*?8)?:6@-6@G)A-)AG)B-)BG)C-)C:6D-6D<*DA*DF*E-)E/)E2)E9*EG)F-)F/)F2)FF*G-)G/-G9*GE)GG)H-)H4)H8)H;)HD)HG)I-)I5)I8-IC)IG)J-)J0*J6+J<-JB)JG)K-)K8-KA)KG)L-)L8)L<)M-)M0*MF+N-)NG)O-)OE-P-)P0*P8)P=*PE-Q-)Q81QF+R-)R7)R9)R<)R@)RG)S-)S0*S6)S9)S<)S@)T-)T0*T6)T9)T=*TE-U-)U0*U7)U:*UE*V-)V0*VE*W-*W0)W39WE*XE*", 2, "1C*2C*38)45+4<)4C*55+5<*5C*64,6<*74,7=*7C*84,8=*8C*:C*;9);;);C*<0+<9)<;)=3)=9)=;)=A)>3)>9)>;)>A)?3)?9)E3)EA)F3)F9*FA)GB+H0*H9*I0*K0*K6*K=,L0*L6*L=,M7*M=,N0*N7*N=+O0*O8)O=+P<)Q0*R0*", 3, ".;*/5)/8+/<*05+09*0<*15+19*1<):2*;1.;>*<3,<>+=/,=4+=>+>.->4+>>+?/,?4+@;*@?*@C*A.*A2*A6*A:5B.5B=*BA*BE*C0*C4*C8*D;)D>+DC+E4+E8)E;*E>+EB-F4+F8)F;*F>+FB,G4+G8)G;*G>,H5*H<)H>.IA*R8)R:*R=+S7*S:*S=+T7*T:+T?)U8*" }, -- Spades_J
  { 1, "++,,+*,.),1?-+*-.)-G).+,.B).G)/+-/A)/G)0<*0@)0G)1-)14*1?)1G)2,+22)26,2<-2G)3+-31+37)3:03G)4+-41+47+4;*4?,4G)5-)51+56)5;)5?)5B)5G)6,+62)66)6;)6?*6G)72)75)7;)7>+7G)8-)80-8:*8>,8G)9-)90)93)99)9<+9A)9G):-):0):3):8,:?,:G);-);0);3);7);;.;C);G)<-)<0,<6)<<,<D)<G)=-+=5)==*=E+>-)>4)>F*?-+?2*?;5@-8@?*@C*@G)A-+A2*A6*A:*A>*AB*AF*B-*B1*B5*B9*B=*BA*BE+C-)C0*C4*C88D-5DA*DE+E-*E@)EG)F-+F6*F?)FE+G-)G0)G5,G>)GA,GG)H-)H1)H4.H=)HA)HD)HG)I-)I2,I9,IA)ID)IG)J-)J3)J6+J;)JA)JD)JG)K-)K3,K9*K@-KG)L-)L4+L9)L?)LB)M-)M4*M9)M>)MB)MF+N-)N2)N5)N9)N>)NA+NG)O-)O2,O8*O;+OA+OE-P-)P30P=)PA+PE-Q-)Q4-Q;,QB)QF+R-)R5)R?*RG)S-)S4)S7*T-)T3)TE-U-)U2)UF,V-)VF)VH*W-?WF)WH*XF,", 2, ".91/6304016,1<+2:*38*67+85,:4+<4)>.,EC,G@)I>+K<,M;+P;*Q9*R6+R;,S90T43U31", 3, "0>*1:*57+76,8<*94,;4*<7,<A+=0,=8,=@,>5+>9,>?,>D*?4,?9*D:*D=,E/*E2,E8,E=+F1,F9,FA,G1+G:,H?*J=,K7*L;,N;+R9*S5*" }, -- Spades_Q
  { 1, "++*+.*,+-,18,E+-+,-G).+*..*.G)/+*/.*/4)/:)/>)/G)04)09)0;)0>)0G)1-)14*17)19)1;)1=)1G)2,+26/2G)3+-3G)4+-4G)5-)58*5;)5G)6,+66,6;+6G)7G)8-)8?)8G)9-)93)9:)9?*9G):-):2*:7,:=-:G);-);1,;7,;=);A-;G)<-)<0)<3*<7)<:)<=)<A-<G)=-)=/)=7,==)=A)=D)=G)>-*>7)>:)>=)>A)>D)>G)?-)?7)?:0?D,@-8@?.@G)A-+A2*A6*A:*A>*AB*AF*B-*B1*B5*B9*B=*BA*BE+C-)C0.C88D-,D30D=)DG)E-)E0)E3)E7)E:)E=)EF*F-)F0)F3)F7)F:,FE)FG)G-)G/-G7)G:)G=)G@*GD)GG)H-)H/-H7)H:,H@,HG)I-)I3-I:,IA*IG)J-)J4*J:)JA)JG)K-)K5)KG)L-)M-)M7+M;,MF+N-)N9)N;*NG)O-)OE-P-)PE-Q-)Q8/QF+R-)R7)R9)R;)R=)R?*RG)S-)S6)S9)S;)S@)T-)T6)T:)T@)TE*TH*U-)UE*UH*V-)VF,W-+W48WE-XE*XH*", 4, ",C)-B*.B*/B*0B*1B*2B*3B*4B*5B*6B*7B*8B*9B*:B*I1*J1*K1*L1*M1*N1*O1*P1*Q1*R1*S1*T1*U1*V1*W1)", 2, ".5+.9*.<*/5-/;+05,0<*36*3<)45+4<)55+5<*65)74,7:)7<*84395-9;,<1*<8*=2)>/*>2)>8*?0)?2)?8*D;*DB)DD)E;*EB)ED*FB)G;*GB*J6,J;-K63L7*L:)L=,M?)N7*N=+O8)O=+P8)P=*S7*S<,T7+T;-U7*U:*U=+", 3, "0:)16)18)1:)1<);>+<>+=0*=3*=>+>1)>3*>>+?.*?1)?3*D@*DC)DE*E4+E@*EC)F4+F@*FC*G4+H4+R8)R:)R<)R>)S:)" }, -- Spades_K
  { 5, "++G,+G-+G.++.G+/++//?/G+0++0/*03)07)0=)0A)0D*0G+1++1/)11)14)18)1<)1@)1C)1E)1G+2++2/)22)25)29)2;)2?)2B)2E)2G+3++3/*33)36)3:)3>)3A)3D*3G+4++4/)41)44)47)4=)4@)4C)4E)4G+5++5/)52)55)58)5<)5?)5B)5E)5G+6++6/)63)66)69)6;)6>)6A)6E)6G+7++7/)74)77)7:)7=)7@)7E)7G+8++8/)85)88*8;*8?)8E)8G+9++9/)96)98*9;*9>)9E)9G+:++:/):7)::):=):E):G+;++;/);6);8*;;*;>);E);G+<++</*<5)<8*<;*<?)<D*<G+=++=/)=1)=4)=7)=:)==)=@)=C)=E)=G+>++>/)>2*>6)>9)>;)>>)>A*>E)>G+?++?/*?2*?5)?8)?<)??)?A*?D*?G+@++@/)@1)@4)@7)@=)@@)@C)@E)@G+A++A/*A2*A5*A9+A>*AA*AD*AG+B++B/*B2*B5*B9+B>*BA*BD*BG+C++C/)C1)C4)C7)C=)C@)CC)CE)CG+D++D/*D2*D5)D8)D<)D?)DA*DD*DG+E++E/)E2*E6)E9)E;)E>)EA*EE)EG+F++F/)F1)F4)F7)F:)F=)F@)FC)FE)FG+G++G/*G5)G8*G;*G?)GD*GG+H++H/)H6)H8*H;*H>)HE)HG+I++I/)I7)I:)I=)IE)IG+J++J/)J6)J8*J;*J>)JE)JG+K++K/)K5)K8*K;*K?)KE)KG+L++L/)L4)L7)L:)L=)L@)LE)LG+M++M/)M3)M6)M9)M;)M>)MA)ME)MG+N++N/)N2)N5)N8)N<)N?)NB)NE)NG+O++O/)O1)O4)O7)O=)O@)OC)OE)OG+P++P/*P3)P6)P:)P>)PA)PD*PG+Q++Q/)Q2)Q5)Q9)Q;)Q?)QB)QE)QG+R++R/)R1)R4)R8)R<)R@)RC)RE)RG+S++S/*S3)S7)S=)SA)SD*SG+T++T/?TG+U++UG+V+GW+GX+G" }, -- Back_1
}
-- The suit pip out of each ace's corner index, for the empty
-- foundation slots: { width, height, ink index, runs }. Derived per
-- suit, because the four aces do not put it in the same place.
local CARD_PIPS = {
  { 5, 6, 1, "()+))+*(-+(-,*)-)+" }, -- Clubs
  { 5, 6, 3, "(*)))+*(-+(-,)+-*)" }, -- Diamonds
  { 5, 5, 3, "((*(+*)(-*(-+)+,*)" }, -- Hearts
  { 5, 6, 1, "(*)))+*(-+(-,*)-)+" }, -- Spades
}
-- <<< end generated

local BACK = 53           -- CARD_RUNS entry for the card back
local COLUMNS = Klondike.COLUMNS

-- The smallest window that can hold a deal. The cards are drawn at 1:1 and
-- will not scale down -- pixel art at a fractional factor is ruined art -- so
-- below this the game says so rather than drawing a broken board. Worked out
-- once here, and used by both on.resize and the panel that explains it, so
-- the two cannot drift apart.
local MIN_W = 2 * MARGIN + COLUMNS * CARD_W + (COLUMNS - 1) * GAP_MIN
local MIN_H = HUD_H + ROW_GAP * 2 + CARD_H * 2 + MARGIN

-- The felt, and the inks that sit on it. Deliberately dark and green: the
-- cards are a pale cream, so anything light behind them would wash the whole
-- screen out.
local PAGE_BG   = {  22,  78,  50 }
local HUD_BG    = {  14,  46,  30 }
local HUD_RULE  = {  40, 100,  66 }
local SLOT_LINE = {  46, 112,  74 }   -- outline of an empty pile
local SLOT_FILL = {  18,  64,  42 }
local INK       = { 236, 244, 238 }
local INK_DIM   = { 158, 196, 172 }
local PANEL_BG  = {  12,  36,  24 }
local ACCENT    = { 246, 200,  80 }
local SEL_COL   = { 250, 214,  90 }   -- the run you are holding
local DEST_COL  = { 120, 230, 150 }   -- somewhere it can legally go
-- The cursor sits on top of the cards themselves, which are a pale cream, so
-- it has to be dark and saturated rather than bright: white was very nearly
-- invisible against a card face. Blue also keeps it apart from the gold of a
-- held run and the green of a legal destination.
local CURSOR_COL= {  40, 130, 245 }
local RED_INK   = { 240, 120, 120 }

-- Largest first: fitFont walks down until the label measures small enough.
local FONT_STEPS = { 16, 12, 11, 10, 9, 7 }

local ui = { w = 318, h = 212, fits = false }
local game = Klondike.new({ seed = 1 })
local menu = { row = 1, draw = 2, passes = 1, auto = 1 }  -- values index MENU_ROWS opts
                                                          -- draw 2 = three cards, the
                                                          -- traditional deal
local state = "menu"        -- menu | playing | paused | won
local cur   = { where = "tab", a = 1, i = 1 }
local held  = nil           -- a copy of `cur` while a run is picked up
local entropy = 0           -- idle ticks before the first deal; seeds the RNG
local message = nil         -- transient one-line note in the status bar

-- ---------------------------------------------------------------- helpers --

-- Setting a colour is a call and a rect is not, so the current colour is
-- tracked and re-set only when it actually changes. A whole black number card
-- comes out at two colours, because its ink is the same value as its frame.
local curR, curG, curB

local function col(gc, c)
  if c[1] ~= curR or c[2] ~= curG or c[3] ~= curB then
    gc:setColorRGB(c[1], c[2], c[3])
    curR, curG, curB = c[1], c[2], c[3]
  end
end

local function fitFont(gc, text, maxW, style)
  for _, size in ipairs(FONT_STEPS) do
    gc:setFont("sansserif", style or "r", size)
    if gc:getStringWidth(text) <= maxW then return size end
  end
  return FONT_STEPS[#FONT_STEPS]
end

-- The preview renderer anchors text at the top left, so everything is drawn
-- with "top" and centred by hand from getStringHeight. Anchoring "middle"
-- looks right on the device and wrong in `make screenshots`.
local function centreText(gc, text, x, y, w)
  gc:drawString(text, x + math.floor((w - gc:getStringWidth(text)) / 2), y, "top")
end

-- os.time() alone is a poor seed: a handheld that has just been reset can
-- report the same value every launch, which would deal an identical game every
-- time. Mixing in how long the player sat on the title screen fixes that.
--
-- The seed is drawn through math.random rather than used directly, which is
-- also what lets the runtime tests pin a deal: tests/nspire_stub.lua seeds
-- math.random and neutralises math.randomseed, so this reseeding becomes a
-- no-op and the same deal comes out every run.
local function newSeed()
  local t = 0
  if os and os.time then t = os.time() or 0 end
  if os and os.clock then t = t + math.floor((os.clock() or 0) * 1000) end
  math.randomseed(t + entropy * 7919)
  math.random(); math.random()   -- first draws after a reseed are weakly mixed
  return math.random(1, 2147483646)
end

local function options()
  return {
    seed = nil,
    draw = (menu.draw == 1) and 1 or 3,
    maxPasses = (menu.passes == 2) and 3 or nil,
    safeAuto = (menu.auto == 2),
  }
end

local function resetCursor()
  cur = { where = "tab", a = 1, i = #game.tab[1] }
  held = nil
end

local function startGame(seed)
  local o = options()
  o.seed = seed or newSeed()
  game = Klondike.new(o)
  state = "playing"
  message = nil
  resetCursor()
  if game.safeAuto then game:runSafeAuto() end
end

-- ---------------------------------------------------------------- layout --

-- The seven columns and the seven top-row slots share one grid: stock, waste,
-- a deliberate hole, then the four foundations. Both rows land on the same x
-- positions, which is what makes up and down between them mean anything.
local function slotX(slot)
  return ui.x0 + (slot - 1) * (CARD_W + ui.gap)
end

-- Row 1 holds six things across seven slots; slot 3 is the hole between the
-- stock/waste pair and the foundations.
local ROW1_SLOT = { 1, 2, 4, 5, 6, 7 }

local function row1Slot(k) return ROW1_SLOT[k] end

function on.resize(w, h)
  ui.w, ui.h = w, h

  local gap = math.floor((w - 2 * MARGIN - COLUMNS * CARD_W) / (COLUMNS - 1))
  if gap < 0 then gap = 0 end
  if gap > GAP_MAX then gap = GAP_MAX end
  ui.gap = gap
  local contentW = COLUMNS * CARD_W + (COLUMNS - 1) * gap
  ui.x0 = math.floor((w - contentW) / 2)

  ui.topY = HUD_H + ROW_GAP
  ui.tabY = ui.topY + CARD_H + ROW_GAP
  ui.tabH = h - MARGIN - ui.tabY

  ui.fits = (w >= MIN_W) and (h >= MIN_H) and (contentW <= w - 2)

  platform.window:invalidate()
end

-- The face-down and face-up steps for a column holding D face-down cards and U
-- face-up ones, given the height the tableau has to spend on offsets.
--
-- Preference order: keep the face-up step comfortable, and buy room for it by
-- squeezing the face-down block, since those cards show nothing but the same
-- back over and over. Only when that is not enough does the face-up step drop
-- below FAN_UP_MIN.
local function fanSteps(D, U, avail)
  if avail < 0 then avail = 0 end

  local function upFor(d)
    if U <= 1 then return FAN_UP_MAX end
    local room = avail - D * d
    if room < 0 then room = 0 end
    return math.floor(room / (U - 1))
  end

  -- Spend the face-down step down one pixel at a time, stopping as soon as
  -- the face-up step is comfortable again. Jumping straight to the minimum
  -- would give a seven-card column at the deal the same cramped stack of
  -- backs as a nineteen-card one, for no reason.
  local d = FAN_DOWN_MIN
  for try = FAN_DOWN_MAX, FAN_DOWN_MIN, -1 do
    d = try
    if math.min(FAN_UP_MAX, upFor(try)) >= FAN_UP_MIN then break end
  end
  local u = math.min(FAN_UP_MAX, upFor(d))
  if u < 1 then u = 1 end

  -- Whatever the arithmetic above decided, the column must fit. A window
  -- short enough to defeat both minimums shrinks the face-down block to
  -- nothing and then the face-up step, in that order; drawCard clips the rest,
  -- so the tableau area is never overrun however long the column gets.
  local function total() return D * d + ((U > 1) and (U - 1) * u or 0) end
  while total() > avail and d > 0 do d = d - 1 end
  while total() > avail and u > 1 do u = u - 1 end

  return d, u
end

-- Where every card of a column sits, top to bottom. Returned as a flat array
-- of y positions so both the painter and the hit-tester use the same numbers
-- and cannot drift apart.
local function columnYs(c)
  local col, down = game.tab[c], game.down[c]
  local n = #col
  local ys = {}
  if n == 0 then return ys end
  local d, u = fanSteps(down, n - down, ui.tabH - CARD_H)
  local y = ui.tabY
  for i = 1, n do
    ys[i] = y
    if i <= down then y = y + d else y = y + u end
  end
  return ys
end

-- --------------------------------------------------------------- drawing --

local function clippedRect(gc, x, y, w, h, top, bot)
  local y0 = (y < top) and top or y
  local y1 = y + h
  if y1 > bot then y1 = bot end
  if y1 <= y0 or w <= 0 then return end
  gc:fillRect(x, y0, w, y1 - y0)
end

-- Draws card `idx` with its top-left at (ox, oy), showing only the rows
-- between `top` and `bot`. That single clip does three jobs: it is how a
-- fanned card shows just its corner index, how the bottom of a long column is
-- kept inside the tableau, and how nothing is ever drawn over the status bar.
local function drawCard(gc, ox, oy, idx, top, bot)
  if oy >= bot or oy + CARD_H <= top then return end

  col(gc, CARD_BODY)
  for i = 1, #CARD_BODY_RECTS, 4 do
    clippedRect(gc, ox + CARD_BODY_RECTS[i], oy + CARD_BODY_RECTS[i + 1],
                CARD_BODY_RECTS[i + 2], CARD_BODY_RECTS[i + 3], top, bot)
  end
  col(gc, CARD_FRAME)
  for i = 1, #CARD_FRAME_RECTS, 4 do
    clippedRect(gc, ox + CARD_FRAME_RECTS[i], oy + CARD_FRAME_RECTS[i + 1],
                CARD_FRAME_RECTS[i + 2], CARD_FRAME_RECTS[i + 3], top, bot)
  end

  local entry = CARD_RUNS[idx]
  for e = 1, #entry, 2 do
    local ink, s = CARD_INK[entry[e]], entry[e + 1]
    local set = false
    for j = 1, #s, 3 do
      local y = oy + string.byte(s, j) - CARD_PACK
      -- Runs are emitted in row order, so once one is past the bottom of the
      -- visible strip the rest of this colour's runs are too.
      if y >= bot then break end
      if y >= top then
        if not set then col(gc, ink); set = true end
        gc:fillRect(ox + string.byte(s, j + 1) - CARD_PACK, y,
                    string.byte(s, j + 2) - CARD_PACK, 1)
      end
    end
  end
end

-- An empty pile: a dim panel with the outline of a card, and for a foundation
-- the suit it is waiting for. The pip comes out of the art rather than the
-- font, because the Nspire is not guaranteed to carry U+2660-2667 and a
-- missing glyph on this OS is a silent empty box, not an error.
local function drawSlot(gc, x, y, suit)
  col(gc, SLOT_FILL)
  gc:fillRect(x + 1, y + 1, CARD_W - 2, CARD_H - 2)
  col(gc, SLOT_LINE)
  gc:fillRect(x + 1, y, CARD_W - 2, 1)
  gc:fillRect(x + 1, y + CARD_H - 1, CARD_W - 2, 1)
  gc:fillRect(x, y + 1, 1, CARD_H - 2)
  gc:fillRect(x + CARD_W - 1, y + 1, 1, CARD_H - 2)

  if suit then
    local pip = CARD_PIPS[suit]
    local pw, ph, s = pip[1], pip[2], pip[4]
    local px = x + math.floor((CARD_W - pw) / 2)
    local py = y + math.floor((CARD_H - ph) / 2)
    col(gc, CARD_INK[pip[3]])
    for j = 1, #s, 3 do
      gc:fillRect(px + string.byte(s, j + 1) - CARD_PACK,
                  py + string.byte(s, j) - CARD_PACK,
                  string.byte(s, j + 2) - CARD_PACK, 1)
    end
  end
end

-- A ring drawn around a pile or a card. Four rects rather than drawRect,
-- because a two-pixel ring reads at this size and a one-pixel one does not.
local function outline(gc, x, y, w, h, c, thickness)
  local t = thickness or 2
  col(gc, c)
  gc:fillRect(x, y, w, t)
  gc:fillRect(x, y + h - t, w, t)
  gc:fillRect(x, y + t, t, h - 2 * t)
  gc:fillRect(x + w - t, y + t, t, h - 2 * t)
end

-- ------------------------------------------------------------- selection --
--
-- Two-stage, as in chess: left and right move between piles, up and down move
-- within a column's face-up cards -- a player can pick up a run starting
-- anywhere in it, so the cursor has to be able to land anywhere in it. Enter
-- picks up, enter again drops, escape cancels.

local function selMoves(sel)
  if not sel then return {} end
  if sel.where == "tab" then
    if (sel.i or 0) < 1 then return {} end
    return game:movesFrom("tab", sel.a, sel.i)
  elseif sel.where == "waste" then
    return game:movesFrom("waste")
  elseif sel.where == "found" then
    return game:movesFrom("found", sel.a)
  elseif sel.where == "stock" then
    return game:movesFrom("stock")
  end
  return {}
end

local function destKey(m)
  if m.k == "wf" or m.k == "tf" then return "found:" .. m.f end
  if m.k == "wt" or m.k == "tt" or m.k == "ft" then return "tab:" .. m.t end
  return nil
end

-- Every pile the current selection can legally reach. Computed by filtering
-- the rules' own move list rather than by asking a second time in the drawing
-- code, so a highlighted destination and an accepted move cannot disagree --
-- which on a screen this size is the difference between playing and guessing.
local function destSet(sel)
  local d = {}
  for _, m in ipairs(selMoves(sel)) do
    local k = destKey(m)
    if k then d[k] = true end
  end
  return d
end

local function pileKey(sel)
  if not sel then return nil end
  if sel.where == "found" then return "found:" .. sel.a end
  if sel.where == "tab" then return "tab:" .. sel.a end
  return sel.where
end

local function findMove(from, to)
  local want = pileKey(to)
  for _, m in ipairs(selMoves(from)) do
    if destKey(m) == want then return m end
  end
  return nil
end

local function nearestRow1(c)
  local best, bestD = 1, 99
  for k = 1, #ROW1_SLOT do
    local d = math.abs(ROW1_SLOT[k] - c)
    if d < bestD then best, bestD = k, d end
  end
  return best
end

local function row1Index(sel)
  if sel.where == "stock" then return 1 end
  if sel.where == "waste" then return 2 end
  if sel.where == "found" then return 2 + sel.a end
  return nil
end

local function setRow1(k)
  if k < 1 then k = #ROW1_SLOT elseif k > #ROW1_SLOT then k = 1 end
  if k == 1 then cur = { where = "stock" }
  elseif k == 2 then cur = { where = "waste" }
  else cur = { where = "found", a = k - 2 } end
end

local function enterColumn(c)
  cur = { where = "tab", a = c, i = #game.tab[c] }
end

local function navigate(key)
  if cur.where == "tab" then
    if key == "left" then
      enterColumn((cur.a == 1) and COLUMNS or cur.a - 1)
    elseif key == "right" then
      enterColumn((cur.a == COLUMNS) and 1 or cur.a + 1)
    elseif key == "up" then
      -- Walk up the face-up run first; the top of it is the way out.
      if cur.i > game.down[cur.a] + 1 then
        cur.i = cur.i - 1
      else
        setRow1(nearestRow1(cur.a))
      end
    elseif key == "down" then
      if cur.i < #game.tab[cur.a] then cur.i = cur.i + 1 end
    end
  else
    local k = row1Index(cur)
    if key == "left" then setRow1(k - 1)
    elseif key == "right" then setRow1(k + 1)
    elseif key == "down" then enterColumn(row1Slot(k))
    end
  end
end

-- ------------------------------------------------------------------ play --

local function afterMove()
  if game.safeAuto then game:runSafeAuto() end
  if game:isWon() then state = "won" end
  -- The cursor may be pointing past the end of a column that just shrank.
  if cur.where == "tab" then
    local n = #game.tab[cur.a]
    if cur.i > n then cur.i = n end
    if cur.i < game.down[cur.a] + 1 then cur.i = n end
  end
end

local function doMove(m)
  if not game:play(m) then return false end
  held = nil
  message = nil
  afterMove()
  return true
end

local function activate()
  if state ~= "playing" then return end

  if held then
    local m = findMove(held, cur)
    if m then
      doMove(m)
    elseif pileKey(held) == pileKey(cur) then
      held = nil                      -- putting it back where it came from
    else
      held = nil                      -- not a legal target: pick up here instead
      if #selMoves(cur) > 0 then held = { where = cur.where, a = cur.a, i = cur.i } end
    end
    return
  end

  -- The stock has no "pick up": there is only one thing you can do to it.
  if cur.where == "stock" then
    local ms = selMoves(cur)
    if ms[1] then doMove(ms[1]) else message = "no passes left" end
    return
  end

  if #selMoves(cur) > 0 then
    held = { where = cur.where, a = cur.a, i = cur.i }
  else
    message = "nowhere to go"
  end
end

local function undoMove()
  if state == "won" then state = "playing" end
  held = nil
  if game:canUndo() then
    game:undo()
    message = nil
    if cur.where == "tab" then
      local n = #game.tab[cur.a]
      if cur.i > n then cur.i = n end
    end
  else
    message = "nothing to undo"
  end
end

-- ---------------------------------------------------------------- input --

local MENU_ROWS = {
  { label = "Draw",  key = "draw",   opts = { "one card", "three cards" } },
  { label = "Stock", key = "passes", opts = { "unlimited passes", "three passes" } },
  { label = "Safe cards", key = "auto", opts = { "stay put", "go up by themselves" } },
}

local function menuKey(key)
  if key == "up" then
    menu.row = (menu.row == 1) and #MENU_ROWS or menu.row - 1
  elseif key == "down" then
    menu.row = (menu.row == #MENU_ROWS) and 1 or menu.row + 1
  elseif key == "left" or key == "right" then
    local r = MENU_ROWS[menu.row]
    menu[r.key] = (menu[r.key] == 1) and 2 or 1
  end
end

function on.arrowKey(key)
  if state == "menu" then
    menuKey(key)
  elseif state == "playing" then
    navigate(key)
  end
  platform.window:invalidate()
end

function on.enterKey()
  if state == "menu" then
    startGame()
  elseif state == "paused" then
    state = "playing"
  elseif state == "won" then
    startGame()
  else
    activate()
  end
  platform.window:invalidate()
end

function on.escapeKey()
  if state == "playing" then
    if held then held = nil else state = "paused" end
  elseif state == "paused" then
    state = "playing"
  end
  platform.window:invalidate()
end

function on.backspaceKey()
  if state == "playing" or state == "won" then undoMove() end
  platform.window:invalidate()
end

function on.charIn(ch)
  ch = string.lower(ch or "")

  if ch == "m" then
    state = "menu"
  elseif state == "menu" then
    if ch == " " then startGame() end
  elseif ch == "u" then
    undoMove()
  elseif ch == "r" then
    startGame(game.seed)              -- the same deal again, from the top
  elseif ch == "n" then
    startGame()
  elseif ch == "p" then
    if state == "playing" then state = "paused"
    elseif state == "paused" then state = "playing" end
  elseif ch == " " then
    if state == "paused" or state == "won" then on.enterKey() else activate() end
  end

  platform.window:invalidate()
end

-- Clicking picks the card or pile under the point, then does what enter would
-- do with it: with nothing held that is a pick-up, and with a run held it is a
-- drop, so a whole move is two clicks.
local function hit(x, y)
  if y >= ui.topY and y < ui.topY + CARD_H then
    for k = 1, #ROW1_SLOT do
      local sx = slotX(ROW1_SLOT[k])
      if x >= sx and x < sx + CARD_W then
        if k == 1 then return { where = "stock" } end
        if k == 2 then return { where = "waste" } end
        return { where = "found", a = k - 2 }
      end
    end
    -- The hole beside the waste is where the draw-3 spread lands.
    local wx = slotX(2)
    if x >= wx and x < slotX(4) and #game.waste > 0 then return { where = "waste" } end
  elseif y >= ui.tabY then
    for c = 1, COLUMNS do
      local sx = slotX(c)
      if x >= sx and x < sx + CARD_W then
        local ys = columnYs(c)
        -- Cards overlap, so the one under the point is the last one that
        -- starts above it -- the topmost of the stack at that row.
        local pick = 0
        for i = 1, #ys do
          if y >= ys[i] and y < ys[i] + CARD_H then pick = i end
        end
        if pick > 0 and pick <= game.down[c] then pick = #ys end
        return { where = "tab", a = c, i = pick }
      end
    end
  end
  return nil
end

function on.mouseDown(x, y)
  if state == "menu" or state == "paused" or state == "won" then
    on.enterKey()
    return
  end
  local h = hit(x, y)
  if h then
    cur = h
    activate()
  end
  platform.window:invalidate()
end

-- ------------------------------------------------------------- lifecycle --

timer.start(BASE_TICK)

-- Nothing moves on its own in Klondike, so this does not repaint. It exists
-- only to count how long the player sat on the title screen, which goes into
-- the seed.
function on.timer()
  if state == "menu" then entropy = entropy + 1 end
end

function on.deactivate()
  if state == "playing" then state = "paused" end
  platform.window:invalidate()
end

-- ------------------------------------------------------------ the board --

-- Where a pile's outline goes. For a tableau column that is the exposed card,
-- clipped to the tableau, so a highlight never escapes downwards even when the
-- column is long enough that the last card is cut off.
local function pileRect(sel)
  local bot = ui.tabY + ui.tabH
  if sel.where == "stock" then
    return slotX(1), ui.topY, CARD_W, CARD_H
  elseif sel.where == "waste" then
    local n = #game.waste
    local shown = (game.drawCount == 3) and math.min(3, n) or math.min(1, n)
    local x = slotX(2) + math.max(0, shown - 1) * WASTE_FAN
    return x, ui.topY, CARD_W, CARD_H
  elseif sel.where == "found" then
    return slotX(3 + sel.a), ui.topY, CARD_W, CARD_H
  elseif sel.where == "tab" then
    local ys = columnYs(sel.a)
    local n = #ys
    if n == 0 then return slotX(sel.a), ui.tabY, CARD_W, CARD_H end
    local i = sel.i
    if not i or i < 1 or i > n then i = n end
    local y = ys[i]
    local h = math.min(CARD_H, bot - y)
    -- A held run is outlined as one block from its first card to the bottom.
    if i < n then h = math.min(ys[n] + CARD_H, bot) - y end
    return slotX(sel.a), y, CARD_W, math.max(0, h)
  end
end

local function drawWaste(gc)
  local n = #game.waste
  if n == 0 then
    drawSlot(gc, slotX(2), ui.topY, nil)
    return
  end
  -- Draw-3 spreads the turned cards into the gap beside the waste, the way a
  -- real deal does, so you can see what is coming even though only the last
  -- one is playable. Draw-1 has nothing to spread.
  local shown = (game.drawCount == 3) and math.min(3, n) or 1
  for k = shown, 1, -1 do
    local card = game.waste[n - k + 1]
    drawCard(gc, slotX(2) + (shown - k) * WASTE_FAN, ui.topY, card,
             ui.topY, ui.topY + CARD_H)
  end
end

local function drawTopRow(gc, dests)
  -- Stock. An empty stock that can still be recycled keeps its outline; one
  -- that cannot is dimmed to the felt, because that is the game telling you
  -- the passes have run out.
  if #game.stock > 0 then
    drawCard(gc, slotX(1), ui.topY, BACK, ui.topY, ui.topY + CARD_H)
  else
    drawSlot(gc, slotX(1), ui.topY, nil)
    if game:canRecycle() then
      outline(gc, slotX(1), ui.topY, CARD_W, CARD_H, SLOT_LINE, 1)
    end
  end

  drawWaste(gc)

  for f = 1, Klondike.SUITS do
    local x = slotX(3 + f)
    local top = game:foundTop(f)
    if top then
      drawCard(gc, x, ui.topY, top, ui.topY, ui.topY + CARD_H)
    else
      drawSlot(gc, x, ui.topY, f)
    end
    if dests["found:" .. f] then
      outline(gc, x, ui.topY, CARD_W, CARD_H, DEST_COL)
    end
  end
end

local function drawTableau(gc, dests)
  local bot = ui.tabY + ui.tabH
  for c = 1, COLUMNS do
    local col_, ys = game.tab[c], columnYs(c)
    local x = slotX(c)
    if #col_ == 0 then
      drawSlot(gc, x, ui.tabY, nil)
    else
      for i = 1, #col_ do
        -- Only the strip a player can actually see is drawn: the next card
        -- covers everything below its own top edge.
        local top = ys[i]
        local cardBot = math.min(ys[i] + CARD_H, bot)
        if i < #col_ then cardBot = math.min(cardBot, ys[i + 1]) end
        local idx = (i <= game.down[c]) and BACK or col_[i]
        drawCard(gc, x, top, idx, top, cardBot)
      end
    end
    if dests["tab:" .. c] then
      local rx, ry, rw, rh = pileRect({ where = "tab", a = c })
      outline(gc, rx, ry, rw, rh, DEST_COL)
    end
  end
end

-- ----------------------------------------------------------------- HUD --

local function drawHud(gc)
  col(gc, HUD_BG)
  gc:fillRect(0, 0, ui.w, HUD_H)
  col(gc, HUD_RULE)
  gc:fillRect(0, HUD_H - 1, ui.w, 1)

  gc:setFont("sansserif", "r", 10)
  local th = gc:getStringHeight("Ay")
  local ty = math.max(0, math.floor((HUD_H - 1 - th) / 2))

  local left = message or string.format("Score %d", game.score)
  local mid = string.format("%d/52", game:foundationTotal())
  local right = string.format("Moves %d", game.moves)
  if game.maxPasses then
    right = string.format("Pass %d/%d", game.passes, game.maxPasses)
  end

  -- Sized from the font, never from a character count: the handheld's font is
  -- not the one the previews measure with, and a bar laid out against the
  -- wrong number overlaps itself.
  col(gc, message and ACCENT or INK)
  gc:drawString(left, 4, ty, "top")
  local usedL = 4 + gc:getStringWidth(left)

  col(gc, INK_DIM)
  local rw = gc:getStringWidth(right)
  local rx = ui.w - 4 - rw
  if rx > usedL + 8 then gc:drawString(right, rx, ty, "top") else rx = ui.w - 4 end

  local mw = gc:getStringWidth(mid)
  local mx = math.floor((ui.w - mw) / 2)
  if mx > usedL + 6 and mx + mw < rx - 6 then
    col(gc, ACCENT)
    gc:drawString(mid, mx, ty, "top")
  end
end

-- --------------------------------------------------------------- panels --

-- A centred card of text. `lines` are { text, sel = bool, dim = bool }, and
-- `alt` gives shorter wordings for a window too narrow for the first.
local function drawPanel(gc, title, lines)
  local pad = 10
  gc:setFont("sansserif", "b", 16)
  local titleH, titleW = gc:getStringHeight(title), gc:getStringWidth(title)
  gc:setFont("sansserif", "r", 10)
  local lineH = gc:getStringHeight("Ay")

  local availW = ui.w - 8 - pad * 2
  local texts, maxW = {}, titleW
  for i, l in ipairs(lines) do
    local text = l[1]
    for _, shorter in ipairs(l.alt or {}) do
      if gc:getStringWidth(text) <= availW then break end
      text = shorter
    end
    texts[i] = text
    local w = gc:getStringWidth(text)
    if w > maxW then maxW = w end
  end

  local bw = math.min(maxW + pad * 2, ui.w - 8)
  local bh = titleH + 8 + #lines * lineH + pad * 2
  if bh > ui.h - 8 then
    pad = math.max(2, pad - math.ceil((bh - (ui.h - 8)) / 2))
    bh = math.min(titleH + 8 + #lines * lineH + pad * 2, ui.h - 8)
  end
  local bx = math.max(4, math.floor((ui.w - bw) / 2))
  local by = math.max(4, math.floor((ui.h - bh) / 2))

  col(gc, PANEL_BG)
  gc:fillRect(bx, by, bw, bh)
  outline(gc, bx, by, bw, bh, ACCENT, 1)

  gc:setFont("sansserif", "b", 16)
  col(gc, ACCENT)
  centreText(gc, title, bx, by + pad, bw)

  gc:setFont("sansserif", "r", 10)
  local y = by + pad + titleH + 8
  for i, l in ipairs(lines) do
    if y + lineH > by + bh - 2 then break end
    col(gc, l.sel and ACCENT or (l.dim and INK_DIM or INK))
    centreText(gc, texts[i], bx, y, bw)
    y = y + lineH
  end
end

local function menuLines()
  local lines = {}
  for i, r in ipairs(MENU_ROWS) do
    lines[#lines + 1] = {
      r.label .. ": " .. r.opts[menu[r.key]],
      sel = (menu.row == i),
      alt = { r.opts[menu[r.key]] },
    }
  end
  lines[#lines + 1] = { "", dim = true }
  lines[#lines + 1] = { "arrows: choose      enter: deal",
                        alt = { "arrows / enter" }, dim = true }
  return lines
end

local function drawTooSmall(gc)
  drawPanel(gc, "Klondike", {
    { "This window is too small for a deal.", alt = { "Window too small" } },
    { string.format("The cards need %d x %d.", MIN_W, MIN_H),
      alt = { "Make it bigger" }, dim = true },
  })
end

-- ----------------------------------------------------------------- paint --

function on.paint(gc)
  -- The colour memo is per-frame: the runtime hands out a fresh context each
  -- time, so carrying a remembered colour across frames would skip a set that
  -- was actually needed.
  curR, curG, curB = nil, nil, nil

  col(gc, PAGE_BG)
  gc:fillRect(0, 0, ui.w, ui.h)

  if not ui.fits then
    drawTooSmall(gc)
    return
  end

  -- Destinations are highlighted for whatever the cursor is on, held or not.
  -- Not having to pick a card up to find out where it could go is most of what
  -- makes this playable on a screen this size.
  local sel = held or cur
  local dests = (state == "playing") and destSet(sel) or {}

  drawTopRow(gc, dests)
  drawTableau(gc, dests)

  if state == "playing" then
    local rx, ry, rw, rh = pileRect(cur)
    if rh > 0 then outline(gc, rx, ry, rw, rh, CURSOR_COL) end
    if held then
      local hx, hy, hw, hh = pileRect(held)
      if hh > 0 then outline(gc, hx, hy, hw, hh, SEL_COL) end
    end
  end

  drawHud(gc)

  if state == "menu" then
    drawPanel(gc, "Klondike", menuLines())
  elseif state == "paused" then
    drawPanel(gc, "Paused", {
      { "U undo    R restart    N new deal",
        alt = { "U undo  R restart", "U / R / N" }, dim = true },
      { "M menu", dim = true },
      { "enter: back to the game", alt = { "enter" } },
    })
  elseif state == "won" then
    drawPanel(gc, "You win", {
      { string.format("%d moves, score %d", game.moves, game.score),
        alt = { string.format("score %d", game.score) } },
      { "enter: another deal    M: menu", alt = { "enter / M" }, dim = true },
    })
  elseif state == "playing" and game:isStuck() then
    drawPanel(gc, "Stuck", {
      { "No legal moves left.", alt = { "No moves" } },
      { "U undo    N new deal", alt = { "U / N" }, dim = true },
    })
  end
end

on.resize(318, 212)
