#!/usr/bin/env python3
"""Bundle a game's game.lua + main.lua into a single Lua script for luna.

The TI-Nspire has no `require`, so the whole game has to reach the calculator
as one file. This inlines the logic module as an immediately-invoked function
assigned to a local named `Game`, which is what every game's main.lua expects.

`platform.apilevel` is emitted as line 1 because the Nspire reads it before
running the script.

  python3 tools/bundle.py src/snake build/snake.lua
"""

import sys
from pathlib import Path

API_LEVEL = "2.0"

ROOT = Path(__file__).resolve().parent.parent


def build(src_dir: Path, out_path: Path) -> None:
    game_path, main_path = src_dir / "game.lua", src_dir / "main.lua"
    for p in (game_path, main_path):
        if not p.exists():
            raise SystemExit("missing %s" % p)

    game = game_path.read_text(encoding="utf-8").rstrip("\n")
    main = main_path.read_text(encoding="utf-8").rstrip("\n")

    rel = src_dir.relative_to(ROOT) if src_dir.is_absolute() else src_dir

    # Module bodies are inlined without re-indenting so that line numbers in
    # runtime errors stay close to the originals.
    parts = [
        "platform.apilevel = '%s'" % API_LEVEL,
        "",
        "-- ==========================================================",
        "--  Generated by tools/bundle.py -- do not edit this file.",
        "--  Sources: %s/game.lua, %s/main.lua" % (rel, rel),
        "-- ==========================================================",
        "",
        "local Game = (function()",
        game,
        "end)()",
        "",
        main,
        "",
    ]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(parts), encoding="utf-8")


if __name__ == "__main__":
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "src" / "snake"
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "build" / "snake.lua"
    build(src, out)
    print("bundled %s -> %s" % (src, out))
