#!/usr/bin/env python3
"""Bundle a game's logic module + presentation layer into one Lua script.

The TI-Nspire has no `require`, so a whole game has to reach the calculator as
a single file. This inlines the logic module as an immediately-invoked function
assigned to a local, which is exactly what the matching main file expects.

`platform.apilevel` is emitted as line 1 because the Nspire reads it before
running the script.

    python3 tools/bundle.py build/snake.lua          # target defaults to snake
    python3 tools/bundle.py build/flappy.lua flappy
"""

import sys
from pathlib import Path

API_LEVEL = "2.0"

ROOT = Path(__file__).resolve().parent.parent

# Each target names the pure-logic module, the Nspire-facing main file, and the
# local the module is bound to -- the name main.lua opens with `X or require`.
TARGETS = {
    "snake": {
        "module": "src/game.lua",
        "main": "src/main.lua",
        "local": "Game",
        "out": "build/snake.lua",
    },
    "flappy": {
        "module": "src/flappy.lua",
        "main": "src/flappy_main.lua",
        "local": "Flappy",
        "out": "build/flappy.lua",
    },
}


def build(target: str, out_path: Path) -> None:
    spec = TARGETS[target]
    module_path = ROOT / spec["module"]
    main_path = ROOT / spec["main"]

    module = module_path.read_text(encoding="utf-8").rstrip("\n")
    main = main_path.read_text(encoding="utf-8").rstrip("\n")

    # Module bodies are inlined without re-indenting so that line numbers in
    # runtime errors stay close to the originals.
    parts = [
        "platform.apilevel = '%s'" % API_LEVEL,
        "",
        "-- ==========================================================",
        "--  Generated by tools/bundle.py -- do not edit this file.",
        "--  Sources: %s, %s" % (spec["module"], spec["main"]),
        "-- ==========================================================",
        "",
        "local %s = (function()" % spec["local"],
        module,
        "end)()",
        "",
        main,
        "",
    ]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(parts), encoding="utf-8")


if __name__ == "__main__":
    args = sys.argv[1:]
    target = "snake"
    out = None

    for a in args:
        if a in TARGETS:
            target = a
        else:
            out = Path(a)

    if out is None:
        out = ROOT / TARGETS[target]["out"]

    build(target, out)
    print("bundled %s -> %s" % (target, out))
