#!/usr/bin/env python3
"""Turn the Klondike card PNGs into Lua run-length spans, in place in main.lua.

Same reasoning as tools/sprites.py, which does this for the chess pieces: the
Nspire can draw images, but the byte layout image.new() wants is documented
only by TI and a wrong guess paints nothing at all, with no error to chase.
fillRect is API the mock and the PNG renderer already model and already test.

A card is different from a chess piece in one useful way: it is mostly a solid
block of one colour. So the body is drawn as a couple of rects rather than
encoded, the frame -- pixel-identical across all 53 sprites -- is derived once
and drawn as eight more, and only the ink left over is run-encoded. That takes
a 37x52 card from 1924 pixels to about 150 runs.

The runs are packed into printable ASCII, three characters per run (y, x,
length, each offset by 40 so the range lands inside 40..91 -- printable, no
backslash, no quote). That is a third of the source size of a comma-separated
table of numbers, and it decodes with string.byte and nothing else. They are
emitted in row order so the drawing code can stop reading as soon as it passes
the bottom of a fanned card's visible strip.

Runs are grouped by colour, because setting a colour is a call and the rect is
not: the black suits come out at two colours for a whole card, since their ink
is the same value as the frame.

  python3 tools/cardart.py            # rewrites the block in src/klondike/main.lua
  python3 tools/cardart.py --check    # exit 1 if the file is out of date
  python3 tools/cardart.py --emit     # print the block to stdout

Art: "Kin Pixel Playing Cards" by KIN (https://the-wild-kin.itch.io/kin-pixel-playing-cards).
See assets/klondike/README.md for the licence and how it was obtained.
"""

import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ART = ROOT / "assets" / "klondike"
TARGET = ROOT / "src" / "klondike" / "main.lua"

BEGIN = "-- >>> generated by tools/cardart.py -- do not edit by hand"
END = "-- <<< end generated"

W, H = 37, 52
OFFSET = 40
TRANSPARENT = (0, 0, 0, 0)          # keeps every packed byte inside printable 40..91

SUITS = ["Clubs", "Diamonds", "Hearts", "Spades"]
RANKS = ["ACE", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"]


def card_files():
    """The 52 cards in the game's own (suit - 1) * 13 + rank order, then the back."""
    names = [f"{s}_{r}" for s in SUITS for r in RANKS]
    names.append("Back_1")
    return names


def load(name):
    path = ART / f"{name}.png"
    im = Image.open(path).convert("RGBA")
    if im.size != (W, H):
        raise SystemExit(f"{path}: expected {W}x{H}, got {im.size}")
    px = im.load()
    # Fully transparent pixels carry whatever RGB the editor left behind, and
    # the four rounded corners differ between sprites because of it. Normalise,
    # or the rebuild check below compares invisible colours.
    return [[px[x, y] if px[x, y][3] > 0 else TRANSPARENT for x in range(W)]
            for y in range(H)]


def rectangles(mask):
    """Cover a boolean mask with rects: grow each horizontal run downward."""
    m = [row[:] for row in mask]
    out = []
    for y in range(H):
        x = 0
        while x < W:
            if not m[y][x]:
                x += 1
                continue
            x2 = x
            while x2 < W and m[y][x2]:
                x2 += 1
            h = 1
            while y + h < H and all(m[y + h][i] for i in range(x, x2)):
                h += 1
            for dy in range(h):
                for i in range(x, x2):
                    m[y + dy][i] = False
            out.append((x, y, x2 - x, h))
            x = x2
    return out


def pack(runs):
    return "".join(chr(v + OFFSET) for run in runs for v in run)


def build():
    names = card_files()
    sprites = {n: load(n) for n in names}

    # Every sprite has the same silhouette and the same frame -- checked, not
    # assumed, because the whole scheme collapses if one card is a pixel out.
    opaque = [[sprites[names[0]][y][x][3] > 0 for x in range(W)] for y in range(H)]
    for n in names:
        m = sprites[n]
        for y in range(H):
            for x in range(W):
                if (m[y][x][3] > 0) != opaque[y][x]:
                    raise SystemExit(f"{n}: silhouette differs at {x},{y}")

    body_colour = max(
        (c for row in sprites[names[0]] for c in row if c[3] > 0),
        key=lambda c: sum(1 for row in sprites[names[0]] for p in row if p == c),
    )

    # The frame is whatever is the same non-body colour in all 53 sprites and
    # sits on the outline. Derived rather than hardcoded, so re-cutting the art
    # cannot silently leave the frame behind.
    frame_mask = [[False] * W for _ in range(H)]
    edge = lambda x, y: x <= 1 or x >= W - 2 or y <= 1 or y >= H - 2
    first = sprites[names[0]]
    for y in range(H):
        for x in range(W):
            if not edge(x, y) or not opaque[y][x]:
                continue
            c = first[y][x]
            if c == body_colour:
                continue
            if all(sprites[n][y][x] == c for n in names):
                frame_mask[y][x] = True
    frame_colour = None
    for y in range(H):
        for x in range(W):
            if frame_mask[y][x]:
                frame_colour = first[y][x]
                break
        else:
            continue
        break

    body_rects = rectangles(opaque)
    frame_rects = rectangles(frame_mask)

    # Collect the ink: everything opaque that is neither the body nor a frame
    # pixel. Grouped by colour, in row order.
    palette = []
    cards = []
    for n in names:
        m = sprites[n]
        by_colour = {}
        for y in range(H):
            x = 0
            while x < W:
                c = m[y][x]
                if c[3] == 0 or c == body_colour or frame_mask[y][x]:
                    x += 1
                    continue
                start = x
                while (x < W and m[y][x] == c and not frame_mask[y][x]):
                    x += 1
                by_colour.setdefault(c, []).append((y, start, x - start))
        # Frame colour first, so a black card's ink joins the frame's colour
        # block and costs no extra setColorRGB at all.
        order = sorted(by_colour, key=lambda c: (c != frame_colour, c))
        entry = []
        for c in order:
            if c not in palette:
                palette.append(c)
            entry.append((palette.index(c) + 1, by_colour[c]))
        cards.append(entry)

    verify(names, sprites, body_colour, body_rects, frame_colour, frame_rects,
           palette, cards)
    pips = corner_pips(sprites, body_colour, frame_mask, palette)
    return (body_colour, body_rects, frame_colour, frame_rects, palette, cards,
            names, pips)


def corner_pips(sprites, body_colour, frame_mask, palette):
    """The little suit pip from each ace's corner index, for empty foundations.

    Drawn on the empty foundation slots so they say which suit they are
    waiting for. It has to come from the art: the Nspire's font is not
    guaranteed to carry U+2660-2667, and a missing glyph on this OS is a
    silent empty box rather than an error.

    The offset is *derived per suit*, not hardcoded -- the four aces do not
    agree. Diamonds sits a pixel down and to the right of the other three, and
    a single hardcoded box would clip it.
    """
    out = []
    for suit_index, suit in enumerate(SUITS):
        m = sprites[f"{suit}_ACE"]
        ink = [(x, y) for y in range(20) for x in range(10)
               if m[y][x][3] > 0 and m[y][x] != body_colour and not frame_mask[y][x]]
        rows = sorted({y for x, y in ink})
        # The corner index is the rank glyph over the suit pip, with a blank
        # row between. Split on the widest gap and keep the lower half.
        gap_at = max(range(1, len(rows)), key=lambda i: rows[i] - rows[i - 1])
        pip_rows = rows[gap_at:]
        pip = [(x, y) for x, y in ink if y in pip_rows]
        x0, y0 = min(x for x, y in pip), min(y for x, y in pip)
        x1, y1 = max(x for x, y in pip), max(y for x, y in pip)

        colours = {m[y][x] for x, y in pip}
        if len(colours) != 1:
            raise SystemExit(f"{suit}: corner pip is not one colour: {colours}")
        colour = colours.pop()
        if colour not in palette:
            palette.append(colour)

        runs, cells = [], set(pip)
        for y in range(y0, y1 + 1):
            x = x0
            while x <= x1:
                if (x, y) in cells:
                    start = x
                    while x <= x1 and (x, y) in cells:
                        x += 1
                    runs.append((y - y0, start - x0, x - start))
                else:
                    x += 1
        out.append((x1 - x0 + 1, y1 - y0 + 1, palette.index(colour) + 1, runs))
    return out


def verify(names, sprites, body_colour, body_rects, frame_colour, frame_rects,
           palette, cards):
    """Replay the draw calls into a buffer and demand the exact original back.

    This is the whole safety net for the encoder. A dropped run or an off-by-one
    in the packing would show up on the calculator as a card that is subtly
    wrong, and nowhere else.
    """
    for idx, n in enumerate(names):
        buf = [[TRANSPARENT] * W for _ in range(H)]
        for (x, y, w, h) in body_rects:
            for dy in range(h):
                for dx in range(w):
                    buf[y + dy][x + dx] = body_colour
        for (x, y, w, h) in frame_rects:
            for dy in range(h):
                for dx in range(w):
                    buf[y + dy][x + dx] = frame_colour
        for pi, runs in cards[idx]:
            colour = palette[pi - 1]
            for (y, x, ln) in runs:
                for dx in range(ln):
                    buf[y][x + dx] = colour
        if buf != sprites[n]:
            for y in range(H):
                for x in range(W):
                    if buf[y][x] != sprites[n][y][x]:
                        raise SystemExit(
                            f"{n}: rebuild differs at {x},{y}: "
                            f"got {buf[y][x]}, want {sprites[n][y][x]}")
    return True


def lua_rects(rects):
    return ", ".join(str(v) for r in rects for v in r)


def wrap_strings(items, indent):
    return "\n".join(indent + s for s in items)


def generate():
    (body_colour, body_rects, frame_colour, frame_rects, palette, cards,
     names, pips) = build()

    out = [BEGIN,
           '-- Card art: "Kin Pixel Playing Cards" by KIN,',
           "-- https://the-wild-kin.itch.io/kin-pixel-playing-cards -- see",
           "-- assets/klondike/README.md. Regenerate with tools/cardart.py.",
           "--",
           "-- Each card is: the body rects in CARD_BODY, the frame rects in CARD_FRAME,",
           "-- then run-length ink. A run is three characters -- y, x, length, each less",
           "-- CARD_PACK -- and the runs are in row order, so drawCard can stop as soon as",
           "-- it passes the bottom of a fanned card's visible strip.",
           "local CARD_W, CARD_H = %d, %d" % (W, H),
           "local CARD_PACK = %d" % OFFSET,
           "local CARD_BODY  = { %d, %d, %d }" % body_colour[:3],
           "local CARD_FRAME = { %d, %d, %d }" % frame_colour[:3],
           "local CARD_BODY_RECTS  = { %s }" % lua_rects(body_rects),
           "local CARD_FRAME_RECTS = { %s }" % lua_rects(frame_rects),
           "local CARD_INK = {"]
    for c in palette:
        out.append("  { %d, %d, %d }," % c[:3])
    out.append("}")
    out.append("-- Indexed (suit - 1) * 13 + rank, clubs, diamonds, hearts, spades;")
    out.append("-- entry %d is the back." % (len(names)))
    out.append("local CARD_RUNS = {")
    for idx, n in enumerate(names):
        parts = []
        for pi, runs in cards[idx]:
            parts.append('%d, "%s"' % (pi, pack(runs)))
        out.append("  { %s }, -- %s" % (", ".join(parts), n))
    out.append("}")
    out.append("-- The suit pip out of each ace's corner index, for the empty")
    out.append("-- foundation slots: { width, height, ink index, runs }. Derived per")
    out.append("-- suit, because the four aces do not put it in the same place.")
    out.append("local CARD_PIPS = {")
    for i, (w, h, ci, runs) in enumerate(pips):
        out.append('  { %d, %d, %d, "%s" }, -- %s' % (w, h, ci, pack(runs), SUITS[i]))
    out.append("}")
    out.append(END)
    return "\n".join(out)


def splice(source, block):
    start = source.index(BEGIN)
    end = source.index(END) + len(END)
    return source[:start] + block + source[end:]


if __name__ == "__main__":
    block = generate()
    if "--emit" in sys.argv:
        print(block)
        raise SystemExit(0)

    source = TARGET.read_text(encoding="utf-8")
    if BEGIN not in source or END not in source:
        raise SystemExit(f"{TARGET}: no generated block to replace")
    updated = splice(source, block)
    if "--check" in sys.argv:
        if updated != source:
            raise SystemExit(f"{TARGET} is out of date -- run tools/cardart.py")
        print("card art is up to date")
    else:
        TARGET.write_text(updated, encoding="utf-8")
        print("wrote card art into %s (%d bytes)" % (TARGET, len(block)))
