#!/usr/bin/env python3
"""Generate tests/metrics.lua -- per-character text widths for the mock runtime.

Without this, the mock's getStringWidth is a guess while tools/render.py draws
with a real font, so previewed text overflows boxes that would actually fit on
the calculator. Measuring the same font the renderer uses makes the preview
agree with the layout, which is the only way a screenshot is worth trusting.

The handheld's own font is not DejaVu, so this is a stand-in, not a replica --
on hardware the script asks the real getStringWidth and lays out accordingly.
"""

from pathlib import Path

from PIL import ImageFont

SIZES = [7, 9, 10, 11, 12, 16, 24]
STYLES = {"r": "DejaVuSans.ttf", "b": "DejaVuSans-Bold.ttf",
          "i": "DejaVuSans-Oblique.ttf", "bi": "DejaVuSans-BoldOblique.ttf"}
FONT_DIR = Path("/usr/share/fonts/truetype/dejavu")
FALLBACK = {"r": "DejaVuSans.ttf", "b": "DejaVuSans-Bold.ttf",
            "i": "DejaVuSans.ttf", "bi": "DejaVuSans-Bold.ttf"}
OUT = Path("tests/metrics.lua")


def main() -> None:
    lines = [
        "-- Generated by tools/fontmetrics.py -- do not edit.",
        "-- Character advance widths (pixels) keyed by style and font size,",
        "-- so the mock runtime measures text the same way tools/render.py draws it.",
        "return {",
    ]

    for style, fname in STYLES.items():
        path = FONT_DIR / fname
        if not path.exists():
            path = FONT_DIR / FALLBACK[style]
        lines.append("  %s = {" % style)
        for size in SIZES:
            font = ImageFont.truetype(str(path), size)
            widths = []
            for code in range(32, 127):
                ch = chr(code)
                widths.append(int(round(font.getlength(ch))))
            lines.append("    [%d] = {%s}," % (size, ",".join(str(w) for w in widths)))
        lines.append("  },")

    lines.append("}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote %s" % OUT)


if __name__ == "__main__":
    main()
