#!/usr/bin/env python3
"""Turn seven sprites from the fruit sheet into Lua, in place in main.lua.

Two encodings of the same pixels come out of here, and the generator proves
they agree before writing either.

**TI.Image** is the one the handheld actually uses. `image.new` takes a binary
string and `gc:drawImage` blits it, which is 64 draw calls for a full board
instead of a few thousand rects. The byte layout is documented only by TI --
education.ti.com is blocked from this container -- so it came from
wiki.inspired-lua.org/TI.Image, and was then confirmed on a real CX II with
tools/probe/imageprobe2.lua before anything here depended on it. A 20-byte
little-endian header:

    0  u32  pixel width
    4  u32  pixel height
    8  u8   alignment (0)
    9  u8   flags (0)
    10 u16  padding (0)
    12 u32  bytes between raster lines (2 * width)
    16 u16  bits per pixel (16)
    18 u16  planes (1)

then 16-bit little-endian pixels laid out `A RRRRR GGGGG BBBBB` -- RGB555 with
alpha in the TOP bit, where 0 means the pixel is not drawn. Note it is 555 and
not the more usual 565, and the header is 20 bytes and not 16; the probe
established that getting either wrong makes the OS reject the string outright
("image header mismatch") rather than paint something wrong.

**fillRect runs** are the fallback, and they are not a lesser version of the
art -- they are the identical pixels, because this sheet uses only four to
seven colours per sprite and so needs no quantisation at all. They cover the
two cases drawImage cannot: a cell too small to take a native 16x16 sprite
(the computer software can be resized far below the handheld), and an OS that
declines the string form of image.new. Each rect packs into four printable
characters, offset by OFFSET so the range lands inside 40..92.

Every sprite is rebuilt from BOTH encodings and compared against the source
pixels, and the two are compared against each other. A sprite that decodes
wrong is a build failure here rather than a silently wrong picture on the
handheld.

  python3 tools/fruitart.py             # rewrites the block in src/fruits/main.lua
  python3 tools/fruitart.py --check     # exit 1 if the file is out of date
  python3 tools/fruitart.py --emit      # print the block to stdout
  python3 tools/fruitart.py --proof P   # write a contact sheet of both decodes

Art: see assets/fruits/README.md for source and licence.
"""

import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SHEET = ROOT / "assets" / "fruits" / "Fruit+.png"
TARGET = ROOT / "src" / "fruits" / "main.lua"

BEGIN = "-- >>> generated by tools/fruitart.py -- do not edit by hand"
END = "-- <<< end generated"

SIZE = 16          # the sheet's cell, and the sprite the handheld draws
OFFSET = 40        # keeps every packed rect byte inside printable 40..92
MAX_COLOURS = 12   # a sprite past this would want quantising; none of these do

# The seven the game uses, in kind order, as (name, sheet column, sheet row).
#
# The sheet holds 228 sprites, six variants of thirty-eight fruits. These seven
# are chosen to differ in SILHOUETTE as well as colour, because that is what a
# player reads a board by at sixteen pixels and at speed: a round one, a
# crescent, a big loose cluster, a wedge, a teardrop, a triangle and a small
# tight cluster -- in red, yellow, magenta, orange, green, pink and navy. The
# near-misses were deliberately left out: cherry and strawberry are Apple's
# red, pineapple and lemon are Banana's yellow, and the whole orange is
# Apple's circle again, which is why the orange used here is a cut slice.
FRUITS = [
    ("Apple",      0, 0),
    ("Banana",     7, 2),
    ("Grapes",     5, 1),
    ("Orange",     9, 4),
    ("Pear",      10, 1),
    ("Watermelon",26, 3),
    ("Blueberry", 16, 1),
]


# ---------------------------------------------------------------- slicing --

def load_sheet():
    im = Image.open(SHEET).convert("RGBA")
    if im.width % SIZE or im.height % SIZE:
        raise SystemExit("%s is %dx%d, not a whole number of %d cells"
                         % (SHEET, im.width, im.height, SIZE))
    return im


def slice_sprite(sheet, col, row):
    """A sprite as a SIZE x SIZE grid of RGB triples, or None where transparent."""
    if (col + 1) * SIZE > sheet.width or (row + 1) * SIZE > sheet.height:
        raise SystemExit("cell (%d,%d) is off the sheet" % (col, row))
    px = sheet.load()
    ox, oy = col * SIZE, row * SIZE
    out = []
    for y in range(SIZE):
        line = []
        for x in range(SIZE):
            r, g, b, a = px[ox + x, oy + y]
            line.append((r, g, b) if a > 127 else None)
        out.append(line)
    return out


# ------------------------------------------------------------- TI.Image ----

def u16(v):
    return bytes([v & 255, (v >> 8) & 255])


def u32(v):
    return bytes([v & 255, (v >> 8) & 255, (v >> 16) & 255, (v >> 24) & 255])


def to555(c):
    """RGB888 -> the five-bit-per-channel triple the handheld stores."""
    return (c[0] >> 3, c[1] >> 3, c[2] >> 3)


def from555(t):
    """Back out to eight bits the way a 5-bit DAC does, so the comparison
    below is against what will actually be on screen rather than against the
    original, which no 15-bit format could reproduce."""
    return tuple((v << 3) | (v >> 2) for v in t)


def ti_image(grid):
    out = bytearray()
    out += u32(SIZE) + u32(SIZE)
    out += bytes([0, 0]) + u16(0)        # alignment, flags, padding
    out += u32(SIZE * 2)                 # stride
    out += u16(16) + u16(1)              # bits per pixel, planes
    for row in grid:
        for c in row:
            if c is None:
                out += u16(0)            # top bit clear: not drawn
            else:
                r, g, b = to555(c)
                out += u16(0x8000 | (r << 10) | (g << 5) | b)
    return bytes(out)


def read_ti_image(bs):
    """Decode, checking the header the same way the OS does -- the probe showed
    it rejects a bad one -- so a malformed emit fails here first."""
    def rd(o, n):
        v = 0
        for i in range(n):
            v |= bs[o + i] << (8 * i)
        return v

    if len(bs) < 20:
        raise SystemExit("image shorter than its header")
    w, h = rd(0, 4), rd(4, 4)
    if (rd(8, 1), rd(9, 1), rd(10, 2)) != (0, 0, 0):
        raise SystemExit("alignment/flags/padding must be zero")
    if rd(12, 4) != w * 2:
        raise SystemExit("stride is not 2 * width")
    if rd(16, 2) != 16 or rd(18, 2) != 1:
        raise SystemExit("bits-per-pixel or planes wrong")
    if len(bs) != 20 + w * h * 2:
        raise SystemExit("pixel data is the wrong length")

    grid = []
    for y in range(h):
        line = []
        for x in range(w):
            v = rd(20 + (y * w + x) * 2, 2)
            if v & 0x8000:
                line.append(from555(((v >> 10) & 31, (v >> 5) & 31, v & 31)))
            else:
                line.append(None)
        grid.append(line)
    return grid


# ------------------------------------------------------------ fillRect -----

def rectangles(mask):
    """Cover a boolean mask with rects: grow each horizontal run downward."""
    m = [row[:] for row in mask]
    out = []
    for y in range(SIZE):
        x = 0
        while x < SIZE:
            if not m[y][x]:
                x += 1
                continue
            x2 = x
            while x2 < SIZE and m[y][x2]:
                x2 += 1
            h = 1
            while y + h < SIZE and all(m[y + h][i] for i in range(x, x2)):
                h += 1
            for dy in range(h):
                for i in range(x, x2):
                    m[y + dy][i] = False
            out.append((x, y, x2 - x, h))
            x = x2
    return out


def pack(rects):
    return "".join(chr(v + OFFSET) for r in rects for v in r)


def unpack(s):
    return [tuple(ord(c) - OFFSET for c in s[i:i + 4])
            for i in range(0, len(s), 4)]


# -------------------------------------------------------------- emitting ---

def lua_string(bs):
    """Bytes as a Lua string literal: printable where it can be, decimal
    escapes where it cannot. A digit straight after an escape would be eaten
    into it, so those are escaped too."""
    parts = []
    prev_escape = False
    for b in bs:
        printable = 32 <= b < 127 and b not in (34, 39, 92)
        if printable and not (prev_escape and chr(b).isdigit()):
            parts.append(chr(b))
            prev_escape = False
        else:
            parts.append("\\%03d" % b)
            prev_escape = True
    return "".join(parts)


def encode(sheet, name, col, row):
    grid = slice_sprite(sheet, col, row)

    colours = sorted({c for line in grid for c in line if c})
    if not colours:
        raise SystemExit("%s: sprite is entirely transparent" % name)
    if len(colours) > MAX_COLOURS:
        raise SystemExit("%s: %d colours, past the %d this encoder emits flat"
                         % (name, len(colours), MAX_COLOURS))

    # --- TI.Image, and read it straight back ------------------------------
    blob = ti_image(grid)
    decoded = read_ti_image(blob)
    want555 = [[(from555(to555(c)) if c else None) for c in line] for line in grid]
    if decoded != want555:
        raise SystemExit("%s: TI.Image did not round-trip" % name)

    # --- fillRect runs, and rebuild from exactly what gets written --------
    runs = []
    for c in colours:
        mask = [[grid[y][x] == c for x in range(SIZE)] for y in range(SIZE)]
        runs.append(rectangles(mask))

    rebuilt = [[None] * SIZE for _ in range(SIZE)]
    for ci, rs in enumerate(runs):
        for (x, y, w, h) in unpack(pack(rs)):
            for dy in range(h):
                for dx in range(w):
                    if rebuilt[y + dy][x + dx] is not None:
                        raise SystemExit("%s: rects overlap at %d,%d"
                                         % (name, x + dx, y + dy))
                    rebuilt[y + dy][x + dx] = colours[ci]
    if rebuilt != grid:
        raise SystemExit("%s: rects did not rebuild the sprite" % name)

    # --- and the two encodings have to agree with each other --------------
    # This is the check worth the most: two independent decodes of one sprite,
    # neither trusting the other. They differ only where 15-bit colour cannot
    # represent the source, which is bounded below.
    for y in range(SIZE):
        for x in range(SIZE):
            a, b = decoded[y][x], rebuilt[y][x]
            if (a is None) != (b is None):
                raise SystemExit("%s: encodings disagree about alpha at %d,%d"
                                 % (name, x, y))
            if a is not None and a != from555(to555(b)):
                raise SystemExit("%s: encodings disagree about colour at %d,%d"
                                 % (name, x, y))

    worst = 0
    for line, dline in zip(grid, decoded):
        for c, d in zip(line, dline):
            if c:
                worst = max(worst, max(abs(c[t] - d[t]) for t in range(3)))

    for ch in pack([r for rs in runs for r in rs]):
        if not (40 <= ord(ch) <= 92):
            raise SystemExit("%s: packed byte %d escapes printable range"
                             % (name, ord(ch)))

    return {
        "name": name, "grid": grid, "decoded": decoded, "rebuilt": rebuilt,
        "blob": blob, "colours": colours, "runs": runs, "worst": worst,
        "rects": sum(len(r) for r in runs),
    }


def emit(sprites):
    out = [
        BEGIN,
        "-- %d fruits at %dx%d, in two encodings of the same pixels:" % (len(sprites), SIZE, SIZE),
        "--   img   a TI.Image string for image.new + gc:drawImage (one call a fruit)",
        "--   runs  the identical pixels as fillRect rects, grouped by colour,",
        "--         for cells too small for a native sprite and for an OS that",
        "--         will not take the string form of image.new",
        "-- tools/fruitart.py rebuilds both from what it wrote and compares them",
        "-- against the source and against each other.",
        "local ART_SIZE = %d" % SIZE,
        "local ART = {",
    ]
    for s in sprites:
        pal = ", ".join("%d, %d, %d" % c for c in s["colours"])
        out.append('  { name = "%s", rects = %d,' % (s["name"], s["rects"]))
        out.append('    img = "%s",' % lua_string(s["blob"]))
        out.append("    pal = { %s }," % pal)
        out.append("    runs = {")
        for rs in s["runs"]:
            out.append('      "%s",' % pack(rs))
        out.append("    } },")
    out.append("}")
    out.append(END)
    return "\n".join(out)


def proof(sprites, path):
    bg = (34, 39, 52)
    cell = SIZE + 4
    sheet = Image.new("RGB", (cell * len(sprites), cell * 2), bg)
    for i, s in enumerate(sprites):
        for row, key in ((0, "decoded"), (1, "rebuilt")):
            im = Image.new("RGB", (SIZE, SIZE), bg)
            px = im.load()
            for y in range(SIZE):
                for x in range(SIZE):
                    c = s[key][y][x]
                    if c:
                        px[x, y] = c
            sheet.paste(im, (i * cell + 2, row * cell + 2))
    sheet.resize((sheet.width * 6, sheet.height * 6), Image.NEAREST).save(path)


def splice(text, block):
    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < 0:
        raise SystemExit("markers not found in %s" % TARGET)
    return text[:i] + block + text[j + len(END):]


def main(argv):
    sheet = load_sheet()
    sprites = [encode(sheet, *f) for f in FRUITS]
    block = emit(sprites)

    rects = sum(s["rects"] for s in sprites) / len(sprites)
    sys.stderr.write(
        "fruitart: %d fruits at %dx%d; image path %d bytes a sprite, "
        "%d draw calls a board; fallback %.1f rects a sprite, %d a board; "
        "worst channel error from 15-bit colour %d\n"
        % (len(sprites), SIZE, SIZE, len(sprites[0]["blob"]), 64,
           rects, int(rects * 64), max(s["worst"] for s in sprites)))

    if "--proof" in argv:
        proof(sprites, argv[argv.index("--proof") + 1])

    if "--emit" in argv:
        print(block)
        return 0

    current = TARGET.read_text(encoding="utf-8")
    updated = splice(current, block)

    if "--check" in argv:
        if current != updated:
            sys.stderr.write("fruitart: %s is out of date\n" % TARGET)
            return 1
        sys.stderr.write("fruitart: %s is up to date\n" % TARGET)
        return 0

    if current != updated:
        TARGET.write_text(updated, encoding="utf-8")
        sys.stderr.write("fruitart: rewrote %s\n" % TARGET)
    else:
        sys.stderr.write("fruitart: %s already current\n" % TARGET)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
