#!/usr/bin/env python3
"""Turn the chess piece PNGs into Lua run-length spans, in place in main.lua.

The Nspire *can* draw images -- gc:drawImage since apilevel 1.0, with
image.new() building one from a binary string -- but the byte layout of that
string is documented only by TI, and getting it wrong shows up on hardware as
a blank screen with nothing to debug. These sprites do not need it: they are
1-bit masks, three colours in the whole set (transparent, opaque white, opaque
black), and the white and black files are the *same silhouette* in two inks.

So each piece is emitted as horizontal runs and drawn with fillRect, which is
API this repo's mock and PNG renderer already model and already test. A whole
32-piece board costs about a thousand rects in four colours; chess repaints on
input rather than on a timer, so that is a per-keypress cost, not a per-frame
one.

`edge` is a one-pixel rim, the 8-connected dilation of the mask minus the mask
itself. Without it a white piece on a light square and a black piece on a dark
square are both nearly invisible -- see the previews in docs/screenshots.

  python3 tools/sprites.py            # rewrites the block in src/chess/main.lua
  python3 tools/sprites.py --check    # exit 1 if the file is out of date

Art: "Pixel Chess" by brosen (https://brosen.itch.io/pixel-chess).
"""

import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ART = ROOT / "assets" / "chess"
TARGET = ROOT / "src" / "chess" / "main.lua"

BEGIN = "-- >>> generated by tools/sprites.py -- do not edit by hand"
END = "-- <<< end generated"

# Chess.PAWN..Chess.KING are 1..6, and the table below is emitted in that order.
PIECES = ["pawn", "knight", "bishop", "rook", "queen", "king"]
SIZE = 16


def mask(name: str, colour: str):
    path = ART / f"{name}-{colour}-{SIZE}x{SIZE}.png"
    im = Image.open(path).convert("RGBA")
    if im.size != (SIZE, SIZE):
        raise SystemExit(f"{path}: expected {SIZE}x{SIZE}, got {im.size}")
    px = im.load()
    return [[1 if px[x, y][3] > 0 else 0 for x in range(SIZE)] for y in range(SIZE)]


def dilate(m):
    """The 8-connected rim just outside the silhouette."""
    out = [[0] * SIZE for _ in range(SIZE)]
    for y in range(SIZE):
        for x in range(SIZE):
            if m[y][x]:
                continue
            touching = any(
                0 <= y + dy < SIZE and 0 <= x + dx < SIZE and m[y + dy][x + dx]
                for dy in (-1, 0, 1)
                for dx in (-1, 0, 1)
            )
            if touching:
                out[y][x] = 1
    return out


def runs(m):
    """Horizontal spans as a flat y, x, length, y, x, length, ... list."""
    out = []
    for y, row in enumerate(m):
        x = 0
        while x < SIZE:
            if row[x]:
                start = x
                while x < SIZE and row[x]:
                    x += 1
                out += [y, start, x - start]
            else:
                x += 1
    return out


def wrap(values, indent, per_line=24):
    lines = []
    for i in range(0, len(values), per_line):
        lines.append(indent + ", ".join(str(v) for v in values[i:i + per_line]) + ",")
    return "\n".join(lines)


def generate() -> str:
    body = [BEGIN,
            "-- Piece sprites: \"Pixel Chess\" by brosen, https://brosen.itch.io/pixel-chess",
            "-- Each entry is horizontal runs of a 16x16 mask, flattened to y, x, length.",
            "-- `edge` is the one-pixel rim that keeps a piece readable on a square of its",
            "-- own tone. Regenerate with tools/sprites.py after changing the art.",
            "local SPRITE_PX = %d" % SIZE,
            "local SPRITES = {"]

    for name in PIECES:
        white = mask(name, "white")
        black = mask(name, "black")
        if white != black:
            raise SystemExit(
                f"{name}: the white and black files are different silhouettes, so the "
                f"single mask this emitter assumes is wrong")
        body.append("  { -- %s" % name)
        body.append("    fill = {")
        body.append(wrap(runs(white), "      "))
        body.append("    },")
        body.append("    edge = {")
        body.append(wrap(runs(dilate(white)), "      "))
        body.append("    },")
        body.append("  },")

    body.append("}")
    body.append(END)
    return "\n".join(body)


def splice(source: str, block: str) -> str:
    start = source.index(BEGIN)
    end = source.index(END) + len(END)
    return source[:start] + block + source[end:]


if __name__ == "__main__":
    source = TARGET.read_text(encoding="utf-8")
    if BEGIN not in source or END not in source:
        raise SystemExit(f"{TARGET}: no generated block to replace")

    updated = splice(source, generate())
    if "--check" in sys.argv:
        if updated != source:
            raise SystemExit(f"{TARGET} is out of date -- run tools/sprites.py")
        print("sprites are up to date")
    else:
        TARGET.write_text(updated, encoding="utf-8")
        counts = []
        for name in PIECES:
            m = mask(name, "white")
            counts.append("%s %d+%d" % (name, len(runs(m)) // 3, len(runs(dilate(m))) // 3))
        print("wrote sprites into %s (runs fill+edge: %s)" % (TARGET, ", ".join(counts)))
