#!/usr/bin/env python3
"""Bake assets/wordle/*.txt into the dictionary block of src/wordle/game.lua.

The Nspire sandbox has no file I/O, so the dictionary has to travel inside the
.tns as Lua source. Three shapes were measured before picking one (11,417
guesses, on this container, Lua 5.1):

    representation                      source    .tns    parse
    long-bracket string, one word/line   68,523  29,638   0.3 ms
    packed 5-byte string, concat chunks  57,835  28,012   0.2 ms
    base-26 integer table literal        90,198  33,233   3.2 ms

The integer table loses on every axis at once -- 56% more source, 19% more
.tns, and ten times the parse cost, which on a 396 MHz handheld is a visible
pause at launch. 26^5 fitting in a double is true and irrelevant.

Between the two string forms the packed one saves 1.6 KB in the .tns. This
emits the readable one instead: a long-bracket string with one word per line,
so the dictionary stays greppable and diffable in the repo and a bad entry
shows up in review. That costs one byte per word and buys a fixed six-byte
stride, which is what game.lua binary-searches with string.sub -- no
concatenation and no unpacking at load.

  python3 tools/wordlist.py            # rewrites the block in src/wordle/game.lua
  python3 tools/wordlist.py --check    # exit 1 if the file is out of date

Words: see assets/wordle/README.md for where each list came from.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WORDS = ROOT / "assets" / "wordle"
TARGET = ROOT / "src" / "wordle" / "game.lua"

BEGIN = "-- >>> generated by tools/wordlist.py -- do not edit by hand"
END = "-- <<< end generated"

WORD_RE = re.compile(r"^[a-z]{5}$")


def load(name):
    """Reads one list, rejecting anything that isn't five lowercase letters.

    Loudly, not silently: a dropped word is a word the player can never guess,
    and a smuggled six-letter one would break the fixed stride below.
    """
    path = WORDS / name
    words = []
    for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        w = line.strip()
        if not w:
            continue
        if not WORD_RE.match(w):
            raise SystemExit("%s:%d: %r is not five lowercase letters" % (path, n, w))
        words.append(w)
    if len(set(words)) != len(words):
        dupes = sorted({w for w in words if words.count(w) > 1})
        raise SystemExit("%s: duplicate words: %s" % (path, ", ".join(dupes[:10])))
    if words != sorted(words):
        raise SystemExit("%s: not sorted; game.lua binary-searches this" % path)
    return words


def generate() -> str:
    answers = load("answers.txt")
    guesses = load("guesses.txt")

    missing = sorted(set(answers) - set(guesses))
    if missing:
        raise SystemExit(
            "answers.txt has %d words absent from guesses.txt (%s...). Every answer "
            "must be typeable, so guesses.txt has to be the superset."
            % (len(missing), ", ".join(missing[:5])))

    # Assignments, not declarations: game.lua forward-declares these locals at
    # the top so the functions above close over them, and a `local` here would
    # shadow those with a second set nothing else can see.
    #
    # `[[` swallows a newline immediately after it, which is what makes the
    # first word start at byte 1 and every word land on a six-byte stride.
    # tests/wordle/run.lua pins that, because it is the kind of assumption that
    # would otherwise fail silently and shift the whole dictionary by one.
    body = [
        BEGIN,
        "-- Words: see assets/wordle/README.md. Regenerate with tools/wordlist.py.",
        "-- One word per line inside a long string: WORD_STRIDE bytes each, sorted,",
        "-- binary-searched by `find` above. Not a table -- see the tool for the",
        "-- measurements that chose this shape.",
        "ANSWERS = [[",
        "\n".join(answers) + "]]",
        "GUESSES = [[",
        "\n".join(guesses) + "]]",
        "N_ANSWERS = %d" % len(answers),
        "N_GUESSES = %d" % len(guesses),
        END,
    ]
    return "\n".join(body)


if __name__ == "__main__":
    source = TARGET.read_text(encoding="utf-8")
    if BEGIN not in source or END not in source:
        raise SystemExit("%s: no generated block to replace" % TARGET)

    block = generate()
    start = source.index(BEGIN)
    end = source.index(END) + len(END)
    updated = source[:start] + block + source[end:]

    if "--check" in sys.argv:
        if updated != source:
            raise SystemExit("%s is out of date -- run tools/wordlist.py" % TARGET)
        print("word lists are up to date")
    else:
        TARGET.write_text(updated, encoding="utf-8")
        print("wrote %d answers and %d guesses into %s"
              % (len(load("answers.txt")), len(load("guesses.txt")), TARGET))
